/* Generated By:JJTree: Do not edit this line. ASTAddNode.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTAddNode.h"
#include "SPLParserVisitor.h"

  
  ASTAddNode::ASTAddNode(int id) : SimpleNode(id) {
  }
  ASTAddNode::ASTAddNode(SPLParser *parser, int id) : SimpleNode(parser, id) {
  }
  ASTAddNode::~ASTAddNode() {
  }

  /** Accept the visitor. **/
  void ASTAddNode::jjtAccept(SPLParserVisitor *visitor, void* data) const {
    visitor->visit(this, data);
  }

/* JavaCC - OriginalChecksum=1bfd57435416ad546ea719d0a2da4c01 (do not edit this line) */
