/* Generated By:JJTree: Do not edit this line. ASTAndNode.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTAndNode.h"
#include "SPLParserVisitor.h"

  
  ASTAndNode::ASTAndNode(int id) : SimpleNode(id) {
  }
  ASTAndNode::ASTAndNode(SPLParser *parser, int id) : SimpleNode(parser, id) {
  }
  ASTAndNode::~ASTAndNode() {
  }

  /** Accept the visitor. **/
  void ASTAndNode::jjtAccept(SPLParserVisitor *visitor, void* data) const {
    visitor->visit(this, data);
  }

/* JavaCC - OriginalChecksum=017e33f23edd1784f7f46b4a9a7bbb5a (do not edit this line) */
