/* Generated By:JJTree: Do not edit this line. ASTAndNode.h Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include "SimpleNode.h"

class SPLParser;

class ASTAndNode : public SimpleNode {
public: 
  ASTAndNode(int id);
  ASTAndNode(SPLParser *parser, int id);
  virtual ~ASTAndNode();

  /** Accept the visitor. **/
  virtual void jjtAccept(SPLParserVisitor *visitor, void* data) const ;
};

/* JavaCC - OriginalChecksum=04f1beeeac97989f5c34fae03022c785 (do not edit this line) */
