/* Generated By:JJTree: Do not edit this line. ASTBitwiseOrNode.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTBitwiseOrNode.h"
#include "SPLParserVisitor.h"

  
  ASTBitwiseOrNode::ASTBitwiseOrNode(int id) : SimpleNode(id) {
  }
  ASTBitwiseOrNode::ASTBitwiseOrNode(SPLParser *parser, int id) : SimpleNode(parser, id) {
  }
  ASTBitwiseOrNode::~ASTBitwiseOrNode() {
  }

  /** Accept the visitor. **/
  void ASTBitwiseOrNode::jjtAccept(SPLParserVisitor *visitor, void* data) const {
    visitor->visit(this, data);
  }

/* JavaCC - OriginalChecksum=2a3f7623b2174ed1fd91f16967be2c6f (do not edit this line) */
