/* Generated By:JJTree: Do not edit this line. ASTBitwiseXorNode.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTBitwiseXorNode.h"
#include "SPLParserVisitor.h"

  
  ASTBitwiseXorNode::ASTBitwiseXorNode(int id) : SimpleNode(id) {
  }
  ASTBitwiseXorNode::ASTBitwiseXorNode(SPLParser *parser, int id) : SimpleNode(parser, id) {
  }
  ASTBitwiseXorNode::~ASTBitwiseXorNode() {
  }

  /** Accept the visitor. **/
  void ASTBitwiseXorNode::jjtAccept(SPLParserVisitor *visitor, void* data) const {
    visitor->visit(this, data);
  }

/* JavaCC - OriginalChecksum=b1e1916aafde8ed3f7698c92b93b07a9 (do not edit this line) */
