/* Generated By:JJTree: Do not edit this line. ASTCompilationUnit.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTCompilationUnit.h"
#include "SPLParserVisitor.h"

  
  ASTCompilationUnit::ASTCompilationUnit(int id) : SimpleNode(id) {
  }
  ASTCompilationUnit::ASTCompilationUnit(SPLParser *parser, int id) : SimpleNode(parser, id) {
  }
  ASTCompilationUnit::~ASTCompilationUnit() {
  }

  /** Accept the visitor. **/
  void ASTCompilationUnit::jjtAccept(SPLParserVisitor *visitor, void* data) const {
    visitor->visit(this, data);
  }

/* JavaCC - OriginalChecksum=3d71458a3d3b1b3cffb94f00f539b7ae (do not edit this line) */
