/* Generated By:JJTree: Do not edit this line. ASTCompilationUnit.h Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include "SimpleNode.h"

class SPLParser;

class ASTCompilationUnit : public SimpleNode {
public: 
  ASTCompilationUnit(int id);
  ASTCompilationUnit(SPLParser *parser, int id);
  virtual ~ASTCompilationUnit();

  /** Accept the visitor. **/
  virtual void jjtAccept(SPLParserVisitor *visitor, void* data) const ;
};

/* JavaCC - OriginalChecksum=df7a7b182ea02fe7f3ac85e02d7ae734 (do not edit this line) */
