/* Generated By:JJTree: Do not edit this line. ASTDivNode.h Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include "SimpleNode.h"

class SPLParser;

class ASTDivNode : public SimpleNode {
public: 
  ASTDivNode(int id);
  ASTDivNode(SPLParser *parser, int id);
  virtual ~ASTDivNode();

  /** Accept the visitor. **/
  virtual void jjtAccept(SPLParserVisitor *visitor, void* data) const ;
};

/* JavaCC - OriginalChecksum=ea96accd2597f5f25887e48e530f1bc2 (do not edit this line) */
