/* Generated By:JJTree: Do not edit this line. ASTFalseNode.h Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include "SimpleNode.h"

class SPLParser;

class ASTFalseNode : public SimpleNode {
public: 
  ASTFalseNode(int id);
  ASTFalseNode(SPLParser *parser, int id);
  virtual ~ASTFalseNode();

  /** Accept the visitor. **/
  virtual void jjtAccept(SPLParserVisitor *visitor, void* data) const ;
};

/* JavaCC - OriginalChecksum=7757ae95541ea65455a3593fb724aea0 (do not edit this line) */
