/* Generated By:JJTree: Do not edit this line. ASTGTNode.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTGTNode.h"
#include "SPLParserVisitor.h"

  
  ASTGTNode::ASTGTNode(int id) : SimpleNode(id) {
  }
  ASTGTNode::ASTGTNode(SPLParser *parser, int id) : SimpleNode(parser, id) {
  }
  ASTGTNode::~ASTGTNode() {
  }

  /** Accept the visitor. **/
  void ASTGTNode::jjtAccept(SPLParserVisitor *visitor, void* data) const {
    visitor->visit(this, data);
  }

/* JavaCC - OriginalChecksum=6b46962de7c685e17070b5eb270fa9e9 (do not edit this line) */
