/* Generated By:JJTree: Do not edit this line. ASTLENode.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTLENode.h"
#include "SPLParserVisitor.h"

  
  ASTLENode::ASTLENode(int id) : SimpleNode(id) {
  }
  ASTLENode::ASTLENode(SPLParser *parser, int id) : SimpleNode(parser, id) {
  }
  ASTLENode::~ASTLENode() {
  }

  /** Accept the visitor. **/
  void ASTLENode::jjtAccept(SPLParserVisitor *visitor, void* data) const {
    visitor->visit(this, data);
  }

/* JavaCC - OriginalChecksum=d7bcae58e1134a1c5d29ad41a289890a (do not edit this line) */
