/* Generated By:JJTree: Do not edit this line. ASTLTNode.h Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include "SimpleNode.h"

class SPLParser;

class ASTLTNode : public SimpleNode {
public: 
  ASTLTNode(int id);
  ASTLTNode(SPLParser *parser, int id);
  virtual ~ASTLTNode();

  /** Accept the visitor. **/
  virtual void jjtAccept(SPLParserVisitor *visitor, void* data) const ;
};

/* JavaCC - OriginalChecksum=83769392c98e6798a198b994bfa0c8d5 (do not edit this line) */
