/* Generated By:JJTree: Do not edit this line. ASTLTNode.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTLTNode.h"
#include "SPLParserVisitor.h"

  
  ASTLTNode::ASTLTNode(int id) : SimpleNode(id) {
  }
  ASTLTNode::ASTLTNode(SPLParser *parser, int id) : SimpleNode(parser, id) {
  }
  ASTLTNode::~ASTLTNode() {
  }

  /** Accept the visitor. **/
  void ASTLTNode::jjtAccept(SPLParserVisitor *visitor, void* data) const {
    visitor->visit(this, data);
  }

/* JavaCC - OriginalChecksum=0ae561a9a66b6e9e4b0585c14785e761 (do not edit this line) */
