/* Generated By:JJTree: Do not edit this line. ASTMulNode.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTMulNode.h"
#include "SPLParserVisitor.h"

  
  ASTMulNode::ASTMulNode(int id) : SimpleNode(id) {
  }
  ASTMulNode::ASTMulNode(SPLParser *parser, int id) : SimpleNode(parser, id) {
  }
  ASTMulNode::~ASTMulNode() {
  }

  /** Accept the visitor. **/
  void ASTMulNode::jjtAccept(SPLParserVisitor *visitor, void* data) const {
    visitor->visit(this, data);
  }

/* JavaCC - OriginalChecksum=f2eb5fdee3c2e703f13733751e944e6d (do not edit this line) */
