/* Generated By:JJTree: Do not edit this line. ASTMulNode.h Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include "SimpleNode.h"

class SPLParser;

class ASTMulNode : public SimpleNode {
public: 
  ASTMulNode(int id);
  ASTMulNode(SPLParser *parser, int id);
  virtual ~ASTMulNode();

  /** Accept the visitor. **/
  virtual void jjtAccept(SPLParserVisitor *visitor, void* data) const ;
};

/* JavaCC - OriginalChecksum=e278ac90154691855b5a493f172aa514 (do not edit this line) */
