/* Generated By:JJTree: Do not edit this line. ASTNENode.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTNENode.h"
#include "SPLParserVisitor.h"

  
  ASTNENode::ASTNENode(int id) : SimpleNode(id) {
  }
  ASTNENode::ASTNENode(SPLParser *parser, int id) : SimpleNode(parser, id) {
  }
  ASTNENode::~ASTNENode() {
  }

  /** Accept the visitor. **/
  void ASTNENode::jjtAccept(SPLParserVisitor *visitor, void* data) const {
    visitor->visit(this, data);
  }

/* JavaCC - OriginalChecksum=7f2ab637576a1ca165d7375e96c75b53 (do not edit this line) */
