/* Generated By:JJTree: Do not edit this line. ASTOrNode.h Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include "SimpleNode.h"

class SPLParser;

class ASTOrNode : public SimpleNode {
public: 
  ASTOrNode(int id);
  ASTOrNode(SPLParser *parser, int id);
  virtual ~ASTOrNode();

  /** Accept the visitor. **/
  virtual void jjtAccept(SPLParserVisitor *visitor, void* data) const ;
};

/* JavaCC - OriginalChecksum=de376ca5cb0b50c57439f579af40fbb4 (do not edit this line) */
