/* Generated By:JJTree: Do not edit this line. SimpleNode.h Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include "Node.h"


class SimpleNode : public Node {
public: 
  SimpleNode(int id);
  virtual ~SimpleNode();

  /** Accept the visitor. **/
  virtual void jjtAccept(SPLParserVisitor *visitor, void* data) const ;
};

/* JavaCC - OriginalChecksum=21e3e1e31a171005dbcfdd9a43194bc7 (do not edit this line) */
