/* Generated By:JJTree: Do not edit this line. SimpleNode.h Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include <vector>
#include "JavaCC.h"
#include "Token.h"
#include "Node.h"
#include "SPLParserTreeConstants.h"

class SPLParserVisitor;

class SPLParser;

class SimpleNode : public Node {
protected: 
  std::vector<Node*> children;
  Node*              parent = nullptr;
  void*              value  = nullptr;
//int                numChildren;
  Token*             firstToken = nullptr;
  Token*             lastToken  = nullptr;
  SPLParser*    parser = nullptr;
  int                id = 0;

public: 
           SimpleNode(int id);
           SimpleNode(SPLParser* parser, int id);
  virtual ~SimpleNode();

//#if !NODE_FACTORY
//\#define jjtCreate(id) new SimpleNode(id)
//\#define jjtCreate(p, id) new SimpleNode(p, id)
//#fi

  virtual void           jjtOpen() const;
  virtual void           jjtClose() const;
  virtual void           jjtSetParent(Node *n);
  virtual Node*          jjtGetParent() const;
  virtual void           jjtAddChild(Node *n, int i);
  virtual Node*          jjtGetChild(int i) const;
  virtual int            jjtGetNumChildren() const;
  virtual void           jjtSetValue(void * value);
  virtual void*          jjtGetValue() const;

  virtual Token*         jjtGetFirstToken() const;
  virtual Token*         jjtGetLastToken() const;
  virtual void           jjtSetFirstToken(Token* token);
  virtual void           jjtSetLastToken(Token* token);

  virtual void jjtAccept(SPLParserVisitor *visitor, void* data) const;
  virtual void           jjtChildrenAccept(SPLParserVisitor *visitor, void* data) const;
  virtual void           jjtChildAccept(int childNo, SPLParserVisitor *visitor, void* data) const;

  /* You can override these two methods in subclasses of SimpleNode to
     customize the way the node appears when the tree is dumped.  If
     your output uses more than one line you should override
     toString(string), otherwise overriding toString() is probably all
     you need to do. */
     
  virtual JJString toString() const;
  virtual JJString toString(const JJString& prefix) const;

  /* Override this method if you want to customize how the node dumps
     out its children. */
  virtual void          dump(const JJString& prefix) const;
  virtual void          dumpToBuffer(const JJString& prefix, const JJString& separator, JJString *sb) const;
  virtual int           getId() const { return id;  }
};
/* JavaCC - OriginalChecksum=3ee4383000cbf7611e4e7b872e9aa052 (do not edit this line) */
