/* Generated By:JavaCC: Do not edit this line. SPLParserTokenManager.h Version 8.0.0 */
#pragma once

#include "stdio.h"
#include "JavaCC.h"
#include "CharStream.h"
#include "Token.h"
#include "ErrorHandler.h"
#include "TokenManager.h"
#include "SPLParserConstants.h"

class SPLParser;

/** Token Manager. */
class SPLParserTokenManager : public TokenManager {
public:
#ifndef JAVACC_CHARSTREAM
#define JAVACC_CHARSTREAM CharStream
#endif

private:
  int defaultLexState;
  int curLexState = 0;
  int jjmatchedPos;
  int jjmatchedKind;

  int stateSet[3];
  int newStateSet[3];
  int moved[3];
  int moveIndex;
  unsigned long long jjChars[3][1024];
    
  JJString                  jjimage;
  JJString                  image = jjimage;
  int                       jjimageLen;
  int                       lengthOfMatch;
  JJChar                    curChar;
  JAVACC_CHARSTREAM       * input_stream;

  int                       jjrounds[3];
  int                       jjstateSet[2 * 3];
  TokenManagerErrorHandler* errorHandler;
  bool 						delete_eh;

public: 
  SPLParserTokenManager(JAVACC_CHARSTREAM * stream, int lexState = 0);
  virtual ~SPLParserTokenManager() {}

  Token * getNextToken();

protected:
  bool moveToNextChar();
  
  void ReInit(JAVACC_CHARSTREAM * stream, int lexState = 0);

  void SwitchTo(int lexState);


private:
  void TokenLexicalActions(Token * matchedToken);
  void SkipLexicalActions(Token * matchedToken);
  void MoreLexicalActions();

  int getStartAndSize(int index, int isCount);
  int jjRunStringLiteralMatch();

  int jjMoveNfa(int startState, int curPos);
  Token * jjFillToken();

public:
  void setErrorHandler(TokenManagerErrorHandler *eh) {
      if (delete_eh) delete errorHandler, errorHandler = nullptr;
      delete_eh = false;  // We don't delete stuff passed in.
      errorHandler = eh;
  }
};

/* JavaCC - OriginalChecksum=04679114f9c251bd362058f7119ed56e (do not edit this line) */
