/* Generated By:JavaCC: Do not edit this line. TokenManager.h Version 8.0.0 */
/* JavaCCOptions:STATIC=true,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include <iostream>
#include "JavaCC.h"
#include "Token.h"


/**
 * An implementation for this interface is generated by
 * JavaCCParser.  The user is free to use any implementation
 * of their choice.
 */

class TokenManager {
public:
  virtual       ~TokenManager() { }
  /** This gets the next token from the input stream.
   *  A token of kind 0 (`<EOF>`) should be returned on EOF.
   */
  virtual Token *getNextToken() = 0;
  virtual void   setParser(void* /*parser*/) {};
  virtual void   lexicalError() {
  	std::cerr << "Lexical error encountered." << std::endl;
  }

};

/* JavaCC - OriginalChecksum=2de060404eba41b1f946e8f9ee41d1a7 (do not edit this line) */
