/* Generated By:JavaCC: Do not edit this line. ExpressionTreeConstants.java Version 8.0.0 */
package org.parser;

public interface ExpressionTreeConstants
{
  public final int JJTVOID = 0;
  public final int JJTNIL = 1;
  public final int JJTBOOL = 2;
  public final int JJTUUID = 3;
  public final int JJTREGEXP = 4;
  public final int JJTSTRING = 5;
  public final int JJTOCTAL = 6;
  public final int JJTINTEGER = 7;
  public final int JJTHEXADECIMAL = 8;
  public final int JJTDECIMAL = 9;
  public final int JJTNEGATIVE_INTEGER = 10;
  public final int JJTNEGATIVE_NUMBER = 11;
  public final int JJTLOCALTIME = 12;
  public final int JJTLOCALDATE = 13;
  public final int JJTLOCALDATETIME = 14;
  public final int JJTOFFSETTIME = 15;
  public final int JJTOFFSETDATETIME = 16;
  public final int JJTEWKT = 17;
  public final int JJTCOORDINATE = 18;
  public final int JJTCOORDINATEARRAY = 19;
  public final int JJTPOINT = 20;
  public final int JJTLINESTRING = 21;
  public final int JJTPOLYGON = 22;
  public final int JJTMULTIPOINT = 23;
  public final int JJTMULTILINESTRING = 24;
  public final int JJTMULTIPOLYGON = 25;
  public final int JJTGEOMETRYCOLLECTION = 26;
  public final int JJTENVELOPE = 27;
  public final int JJTIDENTIFIER = 28;
  public final int JJTIDENTIFIER_QUOTED = 29;
  public final int JJTDE9IM = 30;
  public final int JJTLENGTH_UNITS = 31;
  public final int JJTNAME = 32;
  public final int JJTCLASSIFIER = 33;
  public final int JJTLOCALNAME = 34;
  public final int JJTEXPRESSIONLIST = 35;
  public final int JJTBINARYEXPRESSION = 36;
  public final int JJTADDITION = 37;
  public final int JJTSUBTRACTION = 38;
  public final int JJTMULTIPLICATION = 39;
  public final int JJTDIVISION = 40;
  public final int JJTMODULO = 41;
  public final int JJTLITERAL = 42;
  public final int JJTPARAMETER = 43;
  public final int JJTPARAMETERINDEX = 44;
  public final int JJTBINDING = 45;
  public final int JJTATTRIBUTE = 46;
  public final int JJTFUNCTION = 47;
  public final int JJTOR = 48;
  public final int JJTAND = 49;
  public final int JJTNOT = 50;
  public final int JJTSPATIAL_PREDICATE = 51;
  public final int JJTEXISTS = 52;
  public final int JJTEXISTS_OPERATOR = 53;
  public final int JJTNOTEXISTS_OPERATOR = 54;
  public final int JJTRELATIONAL_PREDICATE = 55;
  public final int JJTEQUAL_OPERATOR = 56;
  public final int JJTNOTEQUAL_OPERATOR = 57;
  public final int JJTLESS_OPERATOR = 58;
  public final int JJTLESSEQUAL_OPERATOR = 59;
  public final int JJTGREATER_OPERATOR = 60;
  public final int JJTGREATEREQUAL_OPERATOR = 61;
  public final int JJTISNULL_OPERATOR = 62;
  public final int JJTISNOTNULL_OPERATOR = 63;
  public final int JJTILIKE_OPERATOR = 64;
  public final int JJTLIKE_OPERATOR = 65;
  public final int JJTNOTLIKE_OPERATOR = 66;
  public final int JJTNOTILIKE_OPERATOR = 67;
  public final int JJTBETWEEN_OPERATOR = 68;
  public final int JJTNOTBETWEEN_OPERATOR = 69;
  public final int JJTIN_OPERATOR = 70;
  public final int JJTNOTIN_OPERATOR = 71;
  public final int JJTLITERALLIST = 72;
  public final int JJTST_BBOX_OPERATOR = 73;
  public final int JJTST_RELATE_OPERATOR = 74;
  public final int JJTST_CONTAINS_OPERATOR = 75;
  public final int JJTST_CROSSES_OPERATOR = 76;
  public final int JJTST_DISJOINT_OPERATOR = 77;
  public final int JJTST_EQUALS_OPERATOR = 78;
  public final int JJTST_INTERSECTS_OPERATOR = 79;
  public final int JJTST_OVERLAPS_OPERATOR = 80;
  public final int JJTST_TOUCHES_OPERATOR = 81;
  public final int JJTST_WITHIN_OPERATOR = 82;
  public final int JJTST_BEYOND_OPERATOR = 83;
  public final int JJTST_DWITHIN_OPERATOR = 84;
  public final int JJTSORTLIST = 85;
  public final int JJTSORTASCENDING = 86;
  public final int JJTSORTDESCENDING = 87;


  public static String[] jjtNodeName = {
    "void",
    "NIL",
    "BOOL",
    "UUID",
    "REGEXP",
    "STRING",
    "OCTAL",
    "INTEGER",
    "HEXADECIMAL",
    "DECIMAL",
    "NEGATIVE_INTEGER",
    "NEGATIVE_NUMBER",
    "LOCALTIME",
    "LOCALDATE",
    "LOCALDATETIME",
    "OFFSETTIME",
    "OFFSETDATETIME",
    "EWKT",
    "COORDINATE",
    "COORDINATEARRAY",
    "POINT",
    "LINESTRING",
    "POLYGON",
    "MULTIPOINT",
    "MULTILINESTRING",
    "MULTIPOLYGON",
    "GEOMETRYCOLLECTION",
    "ENVELOPE",
    "IDENTIFIER",
    "IDENTIFIER_QUOTED",
    "DE9IM",
    "LENGTH_UNITS",
    "NAME",
    "CLASSIFIER",
    "LOCALNAME",
    "EXPRESSIONLIST",
    "BINARYEXPRESSION",
    "ADDITION",
    "SUBTRACTION",
    "Multiplication",
    "Division",
    "Modulo",
    "LITERAL",
    "PARAMETER",
    "PARAMETERINDEX",
    "BINDING",
    "ATTRIBUTE",
    "FUNCTION",
    "OR",
    "AND",
    "NOT",
    "SPATIAL_PREDICATE",
    "EXISTS",
    "EXISTS_OPERATOR",
    "NOTEXISTS_OPERATOR",
    "RELATIONAL_PREDICATE",
    "EQUAL_OPERATOR",
    "NOTEQUAL_OPERATOR",
    "LESS_OPERATOR",
    "LESSEQUAL_OPERATOR",
    "GREATER_OPERATOR",
    "GREATEREQUAL_OPERATOR",
    "ISNULL_OPERATOR",
    "ISNOTNULL_OPERATOR",
    "ILIKE_OPERATOR",
    "LIKE_OPERATOR",
    "NOTLIKE_OPERATOR",
    "NOTILIKE_OPERATOR",
    "BETWEEN_OPERATOR",
    "NOTBETWEEN_OPERATOR",
    "IN_OPERATOR",
    "NOTIN_OPERATOR",
    "LITERALLIST",
    "ST_BBOX_OPERATOR",
    "ST_RELATE_OPERATOR",
    "ST_CONTAINS_OPERATOR",
    "ST_CROSSES_OPERATOR",
    "ST_DISJOINT_OPERATOR",
    "ST_EQUALS_OPERATOR",
    "ST_INTERSECTS_OPERATOR",
    "ST_OVERLAPS_OPERATOR",
    "ST_TOUCHES_OPERATOR",
    "ST_WITHIN_OPERATOR",
    "ST_BEYOND_OPERATOR",
    "ST_DWITHIN_OPERATOR",
    "SORTLIST",
    "SORTASCENDING",
    "SORTDESCENDING",
  };
}
/* JavaCC - OriginalChecksum=52f56a068dde804d1275827be4aad86f (do not edit this line) */
