/* Generated By:JJTree,JavaCC: Do not edit this line. ExpressionConstants.java Version 8.0.0 */
package org.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
interface ExpressionConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LP = 11;
  /** RegularExpression Id. */
  int RP = 12;
  /** RegularExpression Id. */
  int LSP = 13;
  /** RegularExpression Id. */
  int RSP = 14;
  /** RegularExpression Id. */
  int DOT = 15;
  /** RegularExpression Id. */
  int COMMA = 16;
  /** RegularExpression Id. */
  int COLON = 17;
  /** RegularExpression Id. */
  int DOLLAR = 18;
  /** RegularExpression Id. */
  int SEMICOLON = 19;
  /** RegularExpression Id. */
  int SIGN = 20;
  /** RegularExpression Id. */
  int DIGIT = 21;
  /** RegularExpression Id. */
  int HEX = 22;
  /** RegularExpression Id. */
  int NULL_TOKEN = 23;
  /** RegularExpression Id. */
  int BOOL_TOKEN = 24;
  /** RegularExpression Id. */
  int OCTAL_TOKEN = 25;
  /** RegularExpression Id. */
  int INTEGER_TOKEN = 26;
  /** RegularExpression Id. */
  int HEXADECIMAL_TOKEN = 27;
  /** RegularExpression Id. */
  int DECIMAL_TOKEN = 28;
  /** RegularExpression Id. */
  int DECIMAL = 29;
  /** RegularExpression Id. */
  int EXPONENT = 30;
  /** RegularExpression Id. */
  int UUID_TOKEN = 31;
  /** RegularExpression Id. */
  int REGEXP_TOKEN = 32;
  /** RegularExpression Id. */
  int STRING_TOKEN = 33;
  /** RegularExpression Id. */
  int LOCALTIME_TOKEN = 34;
  /** RegularExpression Id. */
  int LOCALDATE_TOKEN = 35;
  /** RegularExpression Id. */
  int LOCALDATETIME_TOKEN = 36;
  /** RegularExpression Id. */
  int OFFSETTIME_TOKEN = 37;
  /** RegularExpression Id. */
  int OFFSETDATETIME_TOKEN = 38;
  /** RegularExpression Id. */
  int TIMEZONE = 39;
  /** RegularExpression Id. */
  int SRID_TOKEN = 40;
  /** RegularExpression Id. */
  int POINT_TOKEN = 41;
  /** RegularExpression Id. */
  int POLYGON_TOKEN = 42;
  /** RegularExpression Id. */
  int LINESTRING_TOKEN = 43;
  /** RegularExpression Id. */
  int MULTIPOINT_TOKEN = 44;
  /** RegularExpression Id. */
  int MULTIPOLYGON_TOKEN = 45;
  /** RegularExpression Id. */
  int MULTILINESTRING_TOKEN = 46;
  /** RegularExpression Id. */
  int GEOMETRYCOLLECTION_TOKEN = 47;
  /** RegularExpression Id. */
  int ENVELOPE_TOKEN = 48;
  /** RegularExpression Id. */
  int DE9IM = 49;
  /** RegularExpression Id. */
  int ADD = 50;
  /** RegularExpression Id. */
  int SUB = 51;
  /** RegularExpression Id. */
  int MUL = 52;
  /** RegularExpression Id. */
  int DIV = 53;
  /** RegularExpression Id. */
  int MOD = 54;
  /** RegularExpression Id. */
  int ASC = 55;
  /** RegularExpression Id. */
  int DESC = 56;
  /** RegularExpression Id. */
  int OR = 57;
  /** RegularExpression Id. */
  int AND = 58;
  /** RegularExpression Id. */
  int NOT = 59;
  /** RegularExpression Id. */
  int EQ = 60;
  /** RegularExpression Id. */
  int LT = 61;
  /** RegularExpression Id. */
  int GT = 62;
  /** RegularExpression Id. */
  int NEQ = 63;
  /** RegularExpression Id. */
  int LTE = 64;
  /** RegularExpression Id. */
  int GTE = 65;
  /** RegularExpression Id. */
  int IS = 66;
  /** RegularExpression Id. */
  int IN = 67;
  /** RegularExpression Id. */
  int LIKE = 68;
  /** RegularExpression Id. */
  int ILIKE = 69;
  /** RegularExpression Id. */
  int EXISTS = 70;
  /** RegularExpression Id. */
  int BETWEEN = 71;
  /** RegularExpression Id. */
  int BBOX = 72;
  /** RegularExpression Id. */
  int RELATE = 73;
  /** RegularExpression Id. */
  int EQUALS = 74;
  /** RegularExpression Id. */
  int BEYOND = 75;
  /** RegularExpression Id. */
  int WITHIN = 76;
  /** RegularExpression Id. */
  int DWITHIN = 77;
  /** RegularExpression Id. */
  int TOUCHES = 78;
  /** RegularExpression Id. */
  int CROSSES = 79;
  /** RegularExpression Id. */
  int CONTAINS = 80;
  /** RegularExpression Id. */
  int OVERLAPS = 81;
  /** RegularExpression Id. */
  int DISJOINT = 82;
  /** RegularExpression Id. */
  int INTERSECTS = 83;
  /** RegularExpression Id. */
  int FEET = 84;
  /** RegularExpression Id. */
  int METERS = 85;
  /** RegularExpression Id. */
  int KILOMETERS = 86;
  /** RegularExpression Id. */
  int STATUTE_MILES = 87;
  /** RegularExpression Id. */
  int NAUTICAL_MILES = 88;
  /** RegularExpression Id. */
  int IDENTIFIER_TOKEN = 89;
  /** RegularExpression Id. */
  int IDENTIFIER_QUOTED_TOKEN = 90;
  /** RegularExpression Id. */
  int LETTER = 91;
  /** RegularExpression Id. */
  int DURATION = 92;
  /** RegularExpression Id. */
  int DURATION_DATE = 93;
  /** RegularExpression Id. */
  int DURATION_TIME = 94;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\u000b\"",
    "\"\\f\"",
    "\"\\r\"",
    "\" \"",
    "\"\\u00a0\"",
    "\"\\u2028\"",
    "\"\\u2029\"",
    "\"\\u3000\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\".\"",
    "\",\"",
    "\":\"",
    "\"$\"",
    "\";\"",
    "<SIGN>",
    "<DIGIT>",
    "<HEX>",
    "\"null\"",
    "<BOOL_TOKEN>",
    "<OCTAL_TOKEN>",
    "<INTEGER_TOKEN>",
    "<HEXADECIMAL_TOKEN>",
    "<DECIMAL_TOKEN>",
    "<DECIMAL>",
    "<EXPONENT>",
    "<UUID_TOKEN>",
    "<REGEXP_TOKEN>",
    "<STRING_TOKEN>",
    "<LOCALTIME_TOKEN>",
    "<LOCALDATE_TOKEN>",
    "<LOCALDATETIME_TOKEN>",
    "<OFFSETTIME_TOKEN>",
    "<OFFSETDATETIME_TOKEN>",
    "<TIMEZONE>",
    "\"SRID=\"",
    "\"POINT\"",
    "\"POLYGON\"",
    "\"LINESTRING\"",
    "\"MULTIPOINT\"",
    "\"MULTIPOLYGON\"",
    "\"MULTILINESTRING\"",
    "\"GEOMETRYCOLLECTION\"",
    "\"ENVELOPE\"",
    "<DE9IM>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"ASC\"",
    "\"DESC\"",
    "\"OR\"",
    "\"AND\"",
    "\"NOT\"",
    "<EQ>",
    "<LT>",
    "<GT>",
    "<NEQ>",
    "<LTE>",
    "<GTE>",
    "\"IS\"",
    "\"IN\"",
    "\"LIKE\"",
    "\"ILIKE\"",
    "\"EXISTS\"",
    "\"BETWEEN\"",
    "\"BBOX\"",
    "\"RELATE\"",
    "\"EQUALS\"",
    "\"BEYOND\"",
    "\"WITHIN\"",
    "\"DWITHIN\"",
    "\"TOUCHES\"",
    "\"CROSSES\"",
    "\"CONTAINS\"",
    "\"OVERLAPS\"",
    "\"DISJOINT\"",
    "\"INTERSECTS\"",
    "\"feet\"",
    "\"meters\"",
    "\"kilometers\"",
    "\"statute miles\"",
    "\"nautical miles\"",
    "<IDENTIFIER_TOKEN>",
    "<IDENTIFIER_QUOTED_TOKEN>",
    "<LETTER>",
    "<DURATION>",
    "<DURATION_DATE>",
    "<DURATION_TIME>",
  };
}
/* JavaCC - OriginalChecksum=497107df477d4eda34e069e3769a5f77 (do not edit this line) */
