/* Generated By:JJTree: Do not edit this line. SimpleNode.cc Version 8.0 */
/* JavaCCOptions:MULTI=false,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=false */
#include "SimpleNode.h"

  
  SimpleNode::SimpleNode(int id) : Node(id) {
  }
  SimpleNode::~SimpleNode() {
  }


/* JavaCC - OriginalChecksum=6ebbd7c4ec4c71c02d6def53a537948d (do not edit this line) */
