/* Generated By:JavaCC: Do not edit this line. ToyParserTreeConstants.java Version 7.0.6 */
package toy7;

public interface ToyParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTVOID = 1;
  public int JJTSPECIALBLOCK = 2;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "void",
    "SpecialBlock",
  };
}
/* JavaCC - OriginalChecksum=1ad4104bdf0cbbe4286a22451ed38c37 (do not edit this line) */
