/* Generated By:JavaCC: Do not edit this line. CalcInputParserTokenManager.java Version 8.0.0 */

public class CalcInputParserTokenManager  implements CalcInputParserConstants {

protected static boolean moveToNextChar() {
  try {
    curChar = input_stream.readChar();
  } catch(java.io.IOException e) {
    return false;
  }
  return true;
}

static CalcGUI gui ; static double result = 0.0 ; static boolean firstOperand = true ; private static void ShowResult ( ) { if ( firstOperand ) { image . setLength ( image . length ( ) - 1 ) ; if ( image . length ( ) > 0 ) result = Double . valueOf ( image . toString ( ) ) . doubleValue ( ) ; else result = 0.0 ; firstOperand = false ; } gui . print ( result ) ; } 

    /** Constructor. */
    public CalcInputParserTokenManager(CharStream stream){


    input_stream = stream;
  }

  /** Constructor. */
  public CalcInputParserTokenManager (CharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  
  static public void ReInit(CharStream stream)
  {

    jjmatchedPos = 0;
    curLexState = defaultLexState;
    input_stream = stream;
  }

  /** Reinitialise parser. */
  static public void ReInit(CharStream stream, int lexState)
  
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public static void SwitchTo(int lexState) {
    curLexState = lexState;
  }

private static  int jjRunStringLiteralMatch() {
  int curPos = 0;
  int key = (int)curLexState << 16 | curChar;
  int startState = jjInitStates[curLexState];
  if (startAndSize.containsKey(key)) {
    int[] arr = startAndSize.get(key);
    int index = arr[0];
    for (int i = 0; i < arr[1]; i++) {
      int len = stringLiterals[index++];
      int ignoreCase = stringLiterals[index++];
      do {
        if (curChar != stringLiterals[index + curPos] &&
            (ignoreCase == 0 || curChar != stringLiterals[index + len + curPos])) break;
        if (++curPos == len) break;
        if (!moveToNextChar()) {
          --curPos;
          break;
        }
      } while(curPos < len);
      if (curPos == len) {
        jjmatchedKind = stringLiterals[index + len + (ignoreCase * len)];
        jjmatchedPos = curPos;
        startState = stringLiterals[index + len + (ignoreCase * len) + 1];
        if (!moveToNextChar()) {
          return curPos;
        }
        curPos++;
        break;
      } else {
        index += len + (ignoreCase * len) + 2;
        input_stream.backup(curPos + 1);
        curPos = 0;
        if (!moveToNextChar()) {
          assert(false);
        }
      }
    }
  } else {
  }
  return jjMoveNfa(startState, curPos);
}

private static   int[] stateSet = new int[20];
private static   int[] newStateSet = new int[20];
private static   long[] moved = new long[20];
private static  long moveIndex = 1L;

private static final int jjMoveNfa(int startState, int curPos) {

  if (startState < 0) {
    return curPos;
  }

  // We have a long array indexed by the NFA state number to roughly indicate
  // the input position so when the input reaches part Long.MAX_VALUE (which
  // should be extremely rare), we need to reset them all back to zero.
  if (++moveIndex == Long.MAX_VALUE) {
    for (int i = 0; i < 20; i++) moved[i] = 0L;
    moveIndex = 1L;
  }

  // We initialize the kind to MAX value so that when a match is found, we can
  // simply check if it's less than the current match and store it in that
  // case. This helps implement the 'first occurring' rule properly.
  int cnt = 0;
  stateSet[cnt++] = startState;
  moved[startState] = moveIndex;
 
  // Some NFA states have epsilon transitions (move on empty string). So we
  // just start with all of them. Note that the nextStates array already adds
  // the epsilon closure. Only the initial state needs to do this explicitly.
  for (int s : jjcompositeState[startState]) { 
    if (moved[s] != moveIndex) {
      stateSet[cnt++] = s;
      moved[s] = moveIndex;
    }
  }

  do {
    int newCnt = 0;
    int kind = Integer.MAX_VALUE;
    if (++moveIndex == Long.MAX_VALUE) {
      for (int i = 0; i < 20; i++) moved[i] = 0L;
      moveIndex = 1L;
    }

    int vectorIndex = curChar >> 6;
    long bitpattern = (1L << (curChar & 0x3f));
    do {
      int state = stateSet[--cnt];
      if ((jjChars[state][vectorIndex] & bitpattern) != 0L) {
        // Current input character can move this NFA state. So add all the
        // next states of the current states for use with the next input char.
        for (int newState : jjnextStateSet[state]) {
          if (moved[newState] != moveIndex) {
            // We add each state only once.
            newStateSet[newCnt++] = newState;
            moved[newState] = moveIndex;
          }
        }
        int newKind = jjmatchKinds[state];
        if (kind > newKind) {
          // It's a state so store the matched kind if it's smaller than
          // what's already matched.
          kind = newKind;
        }
      }
    } while (cnt > 0);

    if (kind != Integer.MAX_VALUE) {
      // We found a match. So remember the kind and position of the match.
      jjmatchedKind = kind;
      jjmatchedPos = curPos;
      // Reset the kind to max value so we can contine looking for a longer
      // match.
      kind = Integer.MAX_VALUE;
    }

    // Swap the current and next state sets.
    int[] tmp = stateSet;
    stateSet = newStateSet;
    newStateSet = tmp;
    // Reset the number of states.
    cnt = newCnt;
    if (newCnt == 0) {
      // There were no transitions from any of the current states on the
      // current input. So we are done.
      return curPos;
    }
    // Read the next character and try to continue running the NFA.
    if (!moveToNextChar()) {
      // EOF reached!
      return curPos;
    }
    ++curPos;
  } while (cnt > 0);

  assert(false) :
      "Interal error. Please submit a bug at: http://javacc.java.net.";
  return curPos;
}

private static  int defaultLexState = 0;
protected static  int curLexState = 0;
private static  int jjmatchedPos;
private static  int jjmatchedKind;
private static  StringBuilder jjimage = new StringBuilder();
private static StringBuilder image = jjimage;
private static int jjimageLen;
private static int lengthOfMatch;
protected static int curChar;
protected static  CharStream input_stream;

public static boolean isToken(int kind) {
  return (jjtoToken[kind >> 6] & (1L << (kind & 0x3f))) != 0L;
}

public static final boolean isSkip(int kind) {
  return (jjtoSkip[kind >> 6] & (1L << (kind & 0x3f))) != 0L;
}

public static boolean isSpecial(int kind) {
  return (jjtoSpecial[kind >> 6] & (1L << (kind & 0x3f))) != 0L;
}

public static boolean isMore(int kind) {
  return (jjtoMore[kind >> 6] & (1L << (kind & 0x3f))) != 0L;
}

protected static  Token jjFillToken() {
  Token t;
  String curTokenImage;
  int beginLine;
  int endLine;
  int beginColumn;
  int endColumn;
  if (jjmatchedPos < 0) {
    if (image == null) {
      curTokenImage = "";
    } else {
      curTokenImage = image.toString();
    }
    beginLine = endLine = input_stream.getEndLine();
    beginColumn = endColumn = input_stream.getEndColumn();
  } else {
    String im = jjstrLiteralImages[jjmatchedKind];
    curTokenImage = (im == null) ? input_stream.GetImage() : im;
    beginLine = input_stream.getBeginLine();
    beginColumn = input_stream.getBeginColumn();
    endLine = input_stream.getEndLine();
    endColumn = input_stream.getEndColumn();
  }

   t = Token.newToken(jjmatchedKind);
   t.kind = jjmatchedKind;
   t.image = curTokenImage;

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

/** Get the next Token. */
public static  Token getNextToken() {
  Token specialToken = null;
  Token matchedToken;
  int lastReadPosition = 0;

  EOFLoop:
  for (;;) {
    // First see if we have any input at all.
    try {
      curChar = input_stream.BeginToken();
    } catch(Exception e) {
      // No input. So return EOF token.
      jjmatchedKind = EOF;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      matchedToken.specialToken = specialToken;
      return matchedToken;
    }

    // Set matched kind to a MAX VALUE to implement largest, first occuring rule
    // i.e., smallest kind value matched should be used.
    image = jjimage;
    image.setLength(0);
    jjimageLen = 0;

    MoreLoop: for (;;) {
      jjmatchedKind = Integer.MAX_VALUE;
      jjmatchedPos = 0;
      lastReadPosition = jjRunStringLiteralMatch();
      if (jjmatchedPos == 0 && jjmatchedKind > canMatchAnyChar[curLexState]) {
        jjmatchedKind = canMatchAnyChar[curLexState];
      }

      if (jjmatchedKind != Integer.MAX_VALUE) {
        // We have a match!
  
        // Put back any characters looked ahead.
        input_stream.backup(lastReadPosition - jjmatchedPos);
        if (isToken(jjmatchedKind)) {
          // Matched kind is a real TOKEN.
          matchedToken = jjFillToken();
          matchedToken.specialToken = specialToken;
          TokenLexicalActions(matchedToken);
          if (jjnewLexState[jjmatchedKind] != -1) {
            curLexState = jjnewLexState[jjmatchedKind];
          }
          return matchedToken;
        } else if (isSkip(jjmatchedKind) || isSpecial(jjmatchedKind)) {
          // Matched kind is a SKIP or SPECIAL_TOKEN.
          if (isSpecial(jjmatchedKind)) {
            matchedToken = jjFillToken();
            if (specialToken == null) {
              specialToken = matchedToken;
            } else {
              matchedToken.specialToken = specialToken;
              specialToken = (specialToken.next = matchedToken);
            }
            SkipLexicalActions(matchedToken);
          } else {
            SkipLexicalActions(null);
          }
          if (jjnewLexState[jjmatchedKind] != -1) {
            curLexState = jjnewLexState[jjmatchedKind];
          }
          continue EOFLoop;
        }
        // Here it's a MORE.
        MoreLexicalActions();
        if (jjnewLexState[jjmatchedKind] != -1) {
          curLexState = jjnewLexState[jjmatchedKind];
        }
        lastReadPosition = 0;
        jjmatchedKind = Integer.MAX_VALUE;
        try {
          curChar = input_stream.readChar();
          continue;
        }
        catch (java.io.IOException e1) { }
      }
      reportError(lastReadPosition);
    }
  }
}

protected static  void reportError(int lastReadPosition) {
  int error_line = input_stream.getEndLine();
  int error_column = input_stream.getEndColumn();
  String error_after = null;
  boolean EOFSeen = false;
  try {
    input_stream.readChar();
    input_stream.backup(1);
  } catch (java.io.IOException e1) {
    EOFSeen = true;
    error_after = lastReadPosition <= 1 ? "" : input_stream.GetImage();
    if (curChar == '\n' || curChar == '\r') {
       error_line++;
       error_column = 0;
    }
    else
       error_column++;
  }
  if (!EOFSeen) {
    input_stream.backup(1);
    error_after = lastReadPosition <= 1 ? "" : input_stream.GetImage();
  }
  throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column,
                          error_after, curChar, TokenMgrError.LEXICAL_ERROR);
}

private static final java.util.Map<Integer, int[]> startAndSize =
    new java.util.HashMap<Integer, int[]>();


private static final long[][] jjChars = new long[20][];
private static void InitNfaData() {
  for (int i = 0; i < 20; i++) {
    jjChars[i] = new long[1024];
    int ind = 0;
    // We originally generate something like RLE for the static arrays and
    // we actually expannd them here.
    for (int j = 0; j < jjCharData[i].length; j += 2) {
      for (int k = 0; k < (int)jjCharData[i][j]; k++) {
        jjChars[i][ind++] = jjCharData[i][j + 1];
      }
    }
  }
}
public static String[] lexStateNames = {
"OPERAND"
, 
"REQUIRED_DIGIT"
, 
"OPTIONAL_DIGIT"
, 
"OP_OR_OPERAND"
, 
"OP_LOOP"
, 
"SEEN_PLUS"
, 
"ADD_RIGHT_OPERAND"
, 
"DO_ADD"
, 
"ADD_REQUIRED_DIGIT"
, 
"SEEN_MINUS"
, 
"SUB_RIGHT_OPERAND"
, 
"DO_SUB"
, 
"SUB_REQUIRED_DIGIT"
, 
"SEEN_STAR"
, 
"MUL_RIGHT_OPERAND"
, 
"DO_MUL"
, 
"MUL_REQUIRED_DIGIT"
, 
"SEEN_SLASH"
, 
"DIV_RIGHT_OPERAND"
, 
"DO_DIV"
, 
"DIV_REQUIRED_DIGIT"
};
private static final int[] stringLiterals = {
1, 0, 46, 22, -1, 
1, 0, 46, 22, -1, 
1, 0, 46, 18, -1, 
1, 0, 46, 18, -1, 
1, 0, 42, 7, -1, 
1, 0, 43, 5, -1, 
1, 0, 46, 14, -1, 
1, 0, 43, 5, -1, 
1, 0, 42, 7, -1, 
1, 0, 45, 6, -1, 
1, 0, 42, 7, -1, 
1, 0, 43, 5, -1, 
1, 0, 47, 8, -1, 
1, 0, 46, 14, -1, 
1, 0, 47, 8, -1, 
1, 0, 45, 6, -1, 
1, 0, 47, 8, -1, 
1, 0, 46, 12, -1, 
1, 0, 46, 2, -1, 
1, 0, 45, 6, -1, 
1, 0, 42, 7, -1, 
1, 0, 47, 8, -1, 
1, 0, 45, 6, -1, 
1, 0, 43, 5, -1, 
1, 0, 61, 9, -1, 
1, 0, 46, 26, -1, 
1, 0, 61, 9, -1, 
1, 0, 61, 10, -1, 
1, 0, 61, 9, -1, 
1, 0, 46, 26, -1};
static void InitStringLiteralData() {
startAndSize.put(917550, new int[]{0, 1});
startAndSize.put(852014, new int[]{5, 1});
startAndSize.put(655406, new int[]{10, 1});
startAndSize.put(589870, new int[]{15, 1});
startAndSize.put(131114, new int[]{20, 1});
startAndSize.put(196651, new int[]{25, 1});
startAndSize.put(393262, new int[]{30, 1});
startAndSize.put(131115, new int[]{35, 1});
startAndSize.put(196650, new int[]{40, 1});
startAndSize.put(262189, new int[]{45, 1});
startAndSize.put(42, new int[]{50, 1});
startAndSize.put(43, new int[]{55, 1});
startAndSize.put(262191, new int[]{60, 1});
startAndSize.put(327726, new int[]{65, 1});
startAndSize.put(196655, new int[]{70, 1});
startAndSize.put(45, new int[]{75, 1});
startAndSize.put(131119, new int[]{80, 1});
startAndSize.put(196654, new int[]{85, 1});
startAndSize.put(46, new int[]{90, 1});
startAndSize.put(196653, new int[]{95, 1});
startAndSize.put(262186, new int[]{100, 1});
startAndSize.put(47, new int[]{105, 1});
startAndSize.put(131117, new int[]{110, 1});
startAndSize.put(262187, new int[]{115, 1});
startAndSize.put(262205, new int[]{120, 1});
startAndSize.put(1179694, new int[]{125, 1});
startAndSize.put(61, new int[]{130, 1});
startAndSize.put(196669, new int[]{135, 1});
startAndSize.put(131133, new int[]{140, 1});
startAndSize.put(1114158, new int[]{145, 1});
}
private static final long[][] jjCharData = {
new long[] {1, 287948901175001088L},
new long[] {1, 287948901175001088L},
new long[] {1, 287948901175001088L},
new long[] {1, 287948901175001088L},
new long[] {1, 287948901175001088L},
new long[] {1, 287948901175001088L},
new long[] {1, 287948901175001088L},
new long[] {1, 287948901175001088L},
new long[] {1, 287948901175001088L},
new long[] {1, 287948901175001088L},
new long[] {1, 287948901175001088L},
new long[] {1, 287948901175001088L},
new long[] {1, 287948901175001088L},
new long[] {1, 287948901175001088L},
new long[] {1, 287948901175001088L},
new long[] {1, 287948901175001088L},
new long[] {1, 287948901175001088L},
new long[] {1, 287948901175001088L},
new long[] {1, 287948901175001088L},
new long[] {1, 287948901175001088L}};
private static final int[][] jjcompositeState = {
new int[]{}, 
new int[]{}, 
new int[]{}, 
new int[]{}, 
new int[]{}, 
new int[]{}, 
new int[]{}, 
new int[]{}, 
new int[]{}, 
new int[]{}, 
new int[]{}, 
new int[]{}, 
new int[]{}, 
new int[]{}, 
new int[]{}, 
new int[]{}, 
new int[]{}, 
new int[]{}, 
new int[]{}, 
new int[]{}};
private static final int[] jjmatchKinds = {
1, 
3, 
4, 
11, 
13, 
13, 
15, 
15, 
17, 
17, 
19, 
19, 
21, 
21, 
23, 
23, 
25, 
25, 
27, 
27};
private static final int[][] jjnextStateSet = {
new int[]{}, 
new int[]{}, 
new int[]{}, 
new int[]{}, 
new int[]{}, 
new int[]{}, 
new int[]{}, 
new int[]{}, 
new int[]{}, 
new int[]{}, 
new int[]{}, 
new int[]{}, 
new int[]{}, 
new int[]{}, 
new int[]{}, 
new int[]{}, 
new int[]{}, 
new int[]{}, 
new int[]{}, 
new int[]{}};
private static final int[] jjInitStates  = {
0, 1, 2, 3, -1, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19};
private static final int[] canMatchAnyChar = {
2147483647, 2147483647, 2147483647, 2147483647, 2147483647, 2147483647, 2147483647, 2147483647, 2147483647, 2147483647, 2147483647, 2147483647, 2147483647, 2147483647, 2147483647, 2147483647, 2147483647, 2147483647, 2147483647, 2147483647, 2147483647};
public static final String[] jjstrLiteralImages = {
null
, 
null
, 
"\56", 
null
, 
null
, 
"\53", 
"\55", 
"\52", 
"\57", 
"\75", 
"\75", 
null
, 
"\56", 
null
, 
"\56", 
null
, 
null
, 
null
, 
"\56", 
null
, 
null
, 
null
, 
"\56", 
null
, 
null
, 
null
, 
"\56", 
null
, 
null
};
private static final long[] jjtoSkip = {
1360070624L};
private static final long[] jjtoSpecial = {
1073741824L};
private static final long[] jjtoMore = {
1324283934L};
private static final long[] jjtoToken = {
1073741825L};
private static final int[] jjnewLexState = {
-1, -1, 1, 2, -1, 5, 9, 13, 17, 3, -1, 0, 1, 6, 8, 7, 4, 10, 12, 11, 4, 14, 16, 15, 4, 18, 20, 19, 4};
static void TokenLexicalActions(Token matchedToken) {
  switch(matchedToken.kind) {
    default: break;
  }
}
static void SkipLexicalActions(Token matchedToken) {
  switch(jjmatchedKind) {
    case 5: {

      ShowResult();
      break;
    }
    case 6: {

      ShowResult();
      break;
    }
    case 7: {

      ShowResult();
      break;
    }
    case 8: {

      ShowResult();
      break;
    }
    case 9: {

      ShowResult();
      break;
    }
    case 16: {

      result+=Double.valueOf(image.toString()).doubleValue();
      break;
    }
    case 20: {

      result-=Double.valueOf(image.toString()).doubleValue();
      break;
    }
    case 24: {

      result*=Double.valueOf(image.toString()).doubleValue();
      break;
    }
    case 28: {

      result/=Double.valueOf(image.toString()).doubleValue();
      break;
    }
    default: break;
  }
  switch(jjmatchedKind) {
    default: break;
  }
}
static void MoreLexicalActions() {
jjimageLen += (lengthOfMatch = jjmatchedPos + 1);
  switch(jjmatchedKind) {
    case 11: {

      firstOperand=true;
      break;
    }
    case 12: {

      firstOperand=true;
      break;
    }
    default: break;
  }
}
static {
  InitStringLiteralData();
  InitNfaData(); } 
}
/* JavaCC - OriginalChecksum=aaef695d415359011e481f9853ba577e (do not edit this line) */
