/* Generated By:JavaCC: Do not edit this line. ExpressionTreeConstants.java Version 8.0.0 */
package org.parser;

public interface ExpressionTreeConstants
{
  public final int JJTVOID = 0;
  public final int JJTNIL = 1;
  public final int JJTDECIMAL = 2;
  public final int JJTSTRING = 3;
  public final int JJTIDENTIFIER = 4;
  public final int JJTIDENTIFIER_QUOTED = 5;
  public final int JJTNAME = 6;
  public final int JJTLOCALNAME = 7;
  public final int JJTEXPRESSIONLIST = 8;
  public final int JJTLITERAL = 9;
  public final int JJTATTRIBUTE = 10;
  public final int JJTRELATIONAL_PREDICATE = 11;
  public final int JJTISNULL_OPERATOR = 12;
  public final int JJTISNOTNULL_OPERATOR = 13;


  public static String[] jjtNodeName = {
    "void",
    "NIL",
    "DECIMAL",
    "STRING",
    "IDENTIFIER",
    "IDENTIFIER_QUOTED",
    "NAME",
    "LOCALNAME",
    "EXPRESSIONLIST",
    "LITERAL",
    "ATTRIBUTE",
    "RELATIONAL_PREDICATE",
    "ISNULL_OPERATOR",
    "ISNOTNULL_OPERATOR",
  };
}
/* JavaCC - OriginalChecksum=a524ac3ca51963c12872267d60b66511 (do not edit this line) */
