/* Generated By:JJTree&JavaCC: Do not edit this line. ExpressionConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGenCPP#start()
 */
#ifndef EXPRESSIONCONSTANTS_H
#define EXPRESSIONCONSTANTS_H
#include "JavaCC.h"

  /** End of File. */
const  int _EOF = 0;
  /** RegularExpression Id. */
const  int LP = 7;
  /** RegularExpression Id. */
const  int RP = 8;
  /** RegularExpression Id. */
const  int DOT = 9;
  /** RegularExpression Id. */
const  int COMMA = 10;
  /** RegularExpression Id. */
const  int STRING_TOKEN = 11;
  /** RegularExpression Id. */
const  int IDENTIFIER_TOKEN = 12;
  /** RegularExpression Id. */
const  int IDENTIFIER_QUOTED_TOKEN = 13;
  /** RegularExpression Id. */
const  int INTEGER_TOKEN = 14;
  /** RegularExpression Id. */
const  int DECIMAL_TOKEN = 15;
  /** RegularExpression Id. */
const  int DIGIT = 16;
  /** RegularExpression Id. */
const  int DECIMAL = 17;
  /** RegularExpression Id. */
const  int LETTER = 18;
  /** RegularExpression Id. */
const  int NULL_TOKEN = 19;
  /** RegularExpression Id. */
const  int NOT = 20;
  /** RegularExpression Id. */
const  int IS = 21;

  /** Lexical state. */
const  int DEFAULT = 0;

  /** Literal token values. */
  static const JJChar tokenImage_arr_0[] = 
{0x3c, 0x45, 0x4f, 0x46, 0x3e, 0};
  static const JJChar tokenImage_arr_1[] = 
{0x22, 0x9, 0x22, 0};
  static const JJChar tokenImage_arr_2[] = 
{0x22, 0xa, 0x22, 0};
  static const JJChar tokenImage_arr_3[] = 
{0x22, 0xb, 0x22, 0};
  static const JJChar tokenImage_arr_4[] = 
{0x22, 0xc, 0x22, 0};
  static const JJChar tokenImage_arr_5[] = 
{0x22, 0xd, 0x22, 0};
  static const JJChar tokenImage_arr_6[] = 
{0x22, 0x20, 0x22, 0};
  static const JJChar tokenImage_arr_7[] = 
{0x22, 0x28, 0x22, 0};
  static const JJChar tokenImage_arr_8[] = 
{0x22, 0x29, 0x22, 0};
  static const JJChar tokenImage_arr_9[] = 
{0x22, 0x2e, 0x22, 0};
  static const JJChar tokenImage_arr_10[] = 
{0x22, 0x2c, 0x22, 0};
  static const JJChar tokenImage_arr_11[] = 
{0x22, 0x3c, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x5f, 0x54, 0x4f, 0x4b, 0x45, 0x4e, 0x3e, 0x22, 0};
  static const JJChar tokenImage_arr_12[] = 
{0x22, 0x3c, 0x49, 0x44, 0x45, 0x4e, 0x54, 0x49, 0x46, 0x49, 0x45, 0x52, 0x5f, 0x54, 0x4f, 0x4b, 0x45, 0x4e, 0x3e, 0x22, 0};
  static const JJChar tokenImage_arr_13[] = 
{0x22, 0x3c, 0x49, 0x44, 0x45, 0x4e, 0x54, 0x49, 0x46, 0x49, 0x45, 0x52, 0x5f, 0x51, 0x55, 0x4f, 0x54, 0x45, 0x44, 0x5f, 0x54, 0x4f, 0x4b, 0x45, 0x4e, 0x3e, 0x22, 0};
  static const JJChar tokenImage_arr_14[] = 
{0x22, 0x3c, 0x49, 0x4e, 0x54, 0x45, 0x47, 0x45, 0x52, 0x5f, 0x54, 0x4f, 0x4b, 0x45, 0x4e, 0x3e, 0x22, 0};
  static const JJChar tokenImage_arr_15[] = 
{0x22, 0x3c, 0x44, 0x45, 0x43, 0x49, 0x4d, 0x41, 0x4c, 0x5f, 0x54, 0x4f, 0x4b, 0x45, 0x4e, 0x3e, 0x22, 0};
  static const JJChar tokenImage_arr_16[] = 
{0x22, 0x3c, 0x44, 0x49, 0x47, 0x49, 0x54, 0x3e, 0x22, 0};
  static const JJChar tokenImage_arr_17[] = 
{0x22, 0x3c, 0x44, 0x45, 0x43, 0x49, 0x4d, 0x41, 0x4c, 0x3e, 0x22, 0};
  static const JJChar tokenImage_arr_18[] = 
{0x22, 0x3c, 0x4c, 0x45, 0x54, 0x54, 0x45, 0x52, 0x3e, 0x22, 0};
  static const JJChar tokenImage_arr_19[] = 
{0x22, 0x6e, 0x75, 0x6c, 0x6c, 0x22, 0};
  static const JJChar tokenImage_arr_20[] = 
{0x22, 0x4e, 0x4f, 0x54, 0x22, 0};
  static const JJChar tokenImage_arr_21[] = 
{0x22, 0x49, 0x53, 0x22, 0};
  static const JJChar* const tokenImage[] = {
tokenImage_arr_0, 
tokenImage_arr_1, 
tokenImage_arr_2, 
tokenImage_arr_3, 
tokenImage_arr_4, 
tokenImage_arr_5, 
tokenImage_arr_6, 
tokenImage_arr_7, 
tokenImage_arr_8, 
tokenImage_arr_9, 
tokenImage_arr_10, 
tokenImage_arr_11, 
tokenImage_arr_12, 
tokenImage_arr_13, 
tokenImage_arr_14, 
tokenImage_arr_15, 
tokenImage_arr_16, 
tokenImage_arr_17, 
tokenImage_arr_18, 
tokenImage_arr_19, 
tokenImage_arr_20, 
tokenImage_arr_21, 
  };

#endif
