/* Generated By:JJTree: Do not edit this line. ExpressionTree.h Version 8.0 */
/* JavaCCOptions:MULTI=false,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=false */
#ifndef EXPRESSIONTREE_H
#define EXPRESSIONTREE_H
#include "SimpleNode.h"
#endif 
/* JavaCC - OriginalChecksum=993eac5806ec39c6fe5dbba11a49acab (do not edit this line) */
