/* Generated By:JJTree: Do not edit this line. SimpleNode.h Version 8.0 */
/* JavaCCOptions:MULTI=false,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=false */
#ifndef JAVACC_Expression_SIMPLENODE_H_
#define JAVACC_Expression_SIMPLENODE_H_

#include <vector>
#include "JavaCC.h"
#include "Token.h"
#include "Node.h"
#include "ExpressionTreeConstants.h"


class Expression;

class SimpleNode : public Node {
protected: 
  std::vector<Node*> children;
  Node*              parent = nullptr;
  void*              value  = nullptr;
//int                numChildren;
  Expression*    parser = nullptr;
  int                id = 0;

public: 
           SimpleNode(int id);
           SimpleNode(Expression* parser, int id);
  virtual ~SimpleNode();

//#if !NODE_FACTORY
//\#define jjtCreate(id) new SimpleNode(id)
//\#define jjtCreate(p, id) new SimpleNode(p, id)
//#fi

  virtual void           jjtOpen() const;
  virtual void           jjtClose() const;
  virtual void           jjtSetParent(Node *n);
  virtual Node*          jjtGetParent() const;
  virtual void           jjtAddChild(Node *n, int i);
  virtual Node*          jjtGetChild(int i) const;
  virtual int            jjtGetNumChildren() const;
  virtual void           jjtSetValue(void * value);
  virtual void*          jjtGetValue() const;


  /* You can override these two methods in subclasses of SimpleNode to
     customize the way the node appears when the tree is dumped.  If
     your output uses more than one line you should override
     toString(string), otherwise overriding toString() is probably all
     you need to do. */
     
  virtual JJString toString() const;
  virtual JJString toString(const JJString& prefix) const;

  /* Override this method if you want to customize how the node dumps
     out its children. */
  virtual void          dump(const JJString& prefix) const;
  virtual void          dumpToBuffer(const JJString& prefix, const JJString& separator, JJString *sb) const;
  virtual int           getId() const { return id;  }
};

#endif
/* JavaCC - OriginalChecksum=d294c481d3235c6e2ba9f26683d78d3b (do not edit this line) */
