/* Generated By:JJTree,JavaCC: Do not edit this line. SPLParserConstants.java Version 8.0.0 */
package ast;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SPLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INT = 6;
  /** RegularExpression Id. */
  int BOOL = 7;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 8;
  /** RegularExpression Id. */
  int IDENTIFIER = 41;
  /** RegularExpression Id. */
  int LETTER = 42;
  /** RegularExpression Id. */
  int DIGIT = 43;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"int\"",
    "\"boolean\"",
    "<INTEGER_LITERAL>",
    "\";\"",
    "\"=\"",
    "\"||\"",
    "\"&&\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"~\"",
    "\"!\"",
    "\"(\"",
    "\")\"",
    "\"true\"",
    "\"false\"",
    "\":\"",
    "\"{\"",
    "\"}\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"read\"",
    "\"write\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
  };
}
/* JavaCC - OriginalChecksum=e716291e937dc93896bd357112a98f4e (do not edit this line) */
