/* Generated By:JavaCC: Do not edit this line. SPLParserTreeConstants.java Version 8.0.0 */
package ast;

public interface SPLParserTreeConstants
{
  public final int JJTCOMPILATIONUNIT = 0;
  public final int JJTVARDECLARATION = 1;
  public final int JJTVOID = 2;
  public final int JJTASSIGNMENT = 3;
  public final int JJTORNODE = 4;
  public final int JJTANDNODE = 5;
  public final int JJTBITWISEORNODE = 6;
  public final int JJTBITWISEXORNODE = 7;
  public final int JJTBITWISEANDNODE = 8;
  public final int JJTEQNODE = 9;
  public final int JJTNENODE = 10;
  public final int JJTLTNODE = 11;
  public final int JJTGTNODE = 12;
  public final int JJTLENODE = 13;
  public final int JJTGENODE = 14;
  public final int JJTADDNODE = 15;
  public final int JJTSUBTRACTNODE = 16;
  public final int JJTMULNODE = 17;
  public final int JJTDIVNODE = 18;
  public final int JJTMODNODE = 19;
  public final int JJTBITWISECOMPLNODE = 20;
  public final int JJTNOTNODE = 21;
  public final int JJTID = 22;
  public final int JJTINTCONSTNODE = 23;
  public final int JJTTRUENODE = 24;
  public final int JJTFALSENODE = 25;
  public final int JJTBLOCK = 26;
  public final int JJTSTATEMENTEXPRESSION = 27;
  public final int JJTIFSTATEMENT = 28;
  public final int JJTWHILESTATEMENT = 29;
  public final int JJTREADSTATEMENT = 30;
  public final int JJTWRITESTATEMENT = 31;


  public static String[] jjtNodeName = {
    "CompilationUnit",
    "VarDeclaration",
    "void",
    "Assignment",
    "OrNode",
    "AndNode",
    "BitwiseOrNode",
    "BitwiseXorNode",
    "BitwiseAndNode",
    "EQNode",
    "NENode",
    "LTNode",
    "GTNode",
    "LENode",
    "GENode",
    "AddNode",
    "SubtractNode",
    "MulNode",
    "DivNode",
    "ModNode",
    "BitwiseComplNode",
    "NotNode",
    "Id",
    "IntConstNode",
    "TrueNode",
    "FalseNode",
    "Block",
    "StatementExpression",
    "IfStatement",
    "WhileStatement",
    "ReadStatement",
    "WriteStatement",
  };
}
/* JavaCC - OriginalChecksum=f71e2bf1e2340b82d746f0a60c356e96 (do not edit this line) */
