/* Generated By:JavaCC: Do not edit this line. ToyParserTreeConstants.java Version 8.0.0 */
package toy8;

public interface ToyParserTreeConstants
{
  public final int JJTCOMPILATIONUNIT = 0;
  public final int JJTVOID = 1;
  public final int JJTSPECIALBLOCK = 2;


  public static String[] jjtNodeName = {
    "CompilationUnit",
    "void",
    "SpecialBlock",
  };
}
/* JavaCC - OriginalChecksum=8af4a5e76dd37910ac3f5d4d0771b607 (do not edit this line) */
