/* Generated By:JavaCC: Do not edit this line. SpecialTokenConstants.java Version 8.0.0 */
package special.special8;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SpecialTokenConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NA = 9;
  /** RegularExpression Id. */
  int EOL = 10;
  /** RegularExpression Id. */
  int Id = 13;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int LinesComment = 1;
  /** Lexical state. */
  int LineComment = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"/*\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 8>",
    "<NA>",
    "<EOL>",
    "\"--\"",
    "<token of kind 12>",
    "<Id>",
  };
}
/* JavaCC - OriginalChecksum=dd977d7ebf23d5080618daed60d1c18c (do not edit this line) */
