/* Generated By:JavaCC: Do not edit this line. SpecialTokenConstants.h Version 8.0.0 */

/**
 * Token literal values and constants.
 * Generated by org.javacc.cpp.OtherFilesGenCPP#start()
 */
#ifndef JAVACC_SPECIALTOKENCONSTANTS_H
#define JAVACC_SPECIALTOKENCONSTANTS_H

#include "JavaCC.h"

  /** End of File. */
const  int _EOF = 0;
  /** RegularExpression Id. */
const  int NA = 9;
  /** RegularExpression Id. */
const  int EOL = 10;
  /** RegularExpression Id. */
const  int Id = 13;

  /** Lexical state. */
const  int DEFAULT = 0;
  /** Lexical state. */
const  int LinesComment = 1;
  /** Lexical state. */
const  int LineComment = 2;

  /** Literal token image. */
  static const JJChar tokenImage_0[] = 
{0x3c, 0x45, 0x4f, 0x46, 0x3e, 0};
  static const JJChar tokenImage_1[] = 
{0x20, 0};
  static const JJChar tokenImage_2[] = 
{0x9, 0};
  static const JJChar tokenImage_3[] = 
{0xa, 0};
  static const JJChar tokenImage_4[] = 
{0xd, 0};
  static const JJChar tokenImage_5[] = 
{0x2f, 0x2a, 0};
  static const JJChar tokenImage_6[] = 
{0x2f, 0x2a, 0};
  static const JJChar tokenImage_7[] = 
{0x2a, 0x2f, 0};
  static const JJChar tokenImage_8[] = 
{0x3c, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x20, 0x6f, 0x66, 0x20, 0x6b, 0x69, 0x6e, 0x64, 0x20, 0x38, 0x3e, 0};
  static const JJChar tokenImage_9[] = 
{0x3c, 0x4e, 0x41, 0x3e, 0};
  static const JJChar tokenImage_10[] = 
{0x3c, 0x45, 0x4f, 0x4c, 0x3e, 0};
  static const JJChar tokenImage_11[] = 
{0x2d, 0x2d, 0};
  static const JJChar tokenImage_12[] = 
{0x3c, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x20, 0x6f, 0x66, 0x20, 0x6b, 0x69, 0x6e, 0x64, 0x20, 0x31, 0x32, 0x3e, 0};
  static const JJChar tokenImage_13[] = 
{0x3c, 0x49, 0x64, 0x3e, 0};
  static const JJChar* const tokenImages[] = {
tokenImage_0, 
tokenImage_1, 
tokenImage_2, 
tokenImage_3, 
tokenImage_4, 
tokenImage_5, 
tokenImage_6, 
tokenImage_7, 
tokenImage_8, 
tokenImage_9, 
tokenImage_10, 
tokenImage_11, 
tokenImage_12, 
tokenImage_13, 
  };

  /** Literal token label. */
  static const JJChar tokenLabel_0[] = 
{0x3c, 0x45, 0x4f, 0x46, 0x3e, 0};
  static const JJChar tokenLabel_1[] = 
{0x3c, 0x3e, 0};
  static const JJChar tokenLabel_2[] = 
{0x3c, 0x3e, 0};
  static const JJChar tokenLabel_3[] = 
{0x3c, 0x3e, 0};
  static const JJChar tokenLabel_4[] = 
{0x3c, 0x3e, 0};
  static const JJChar tokenLabel_5[] = 
{0x3c, 0x3e, 0};
  static const JJChar tokenLabel_6[] = 
{0x3c, 0x3e, 0};
  static const JJChar tokenLabel_7[] = 
{0x3c, 0x3e, 0};
  static const JJChar tokenLabel_8[] = 
{0x3c, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x20, 0x6f, 0x66, 0x20, 0x6b, 0x69, 0x6e, 0x64, 0x20, 0x38, 0x3e, 0};
  static const JJChar tokenLabel_9[] = 
{0x3c, 0x4e, 0x41, 0x3e, 0};
  static const JJChar tokenLabel_10[] = 
{0x3c, 0x45, 0x4f, 0x4c, 0x3e, 0};
  static const JJChar tokenLabel_11[] = 
{0x3c, 0x3e, 0};
  static const JJChar tokenLabel_12[] = 
{0x3c, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x20, 0x6f, 0x66, 0x20, 0x6b, 0x69, 0x6e, 0x64, 0x20, 0x31, 0x32, 0x3e, 0};
  static const JJChar tokenLabel_13[] = 
{0x3c, 0x49, 0x64, 0x3e, 0};
  static const JJChar* const tokenLabels[] = {
tokenLabel_0, 
tokenLabel_1, 
tokenLabel_2, 
tokenLabel_3, 
tokenLabel_4, 
tokenLabel_5, 
tokenLabel_6, 
tokenLabel_7, 
tokenLabel_8, 
tokenLabel_9, 
tokenLabel_10, 
tokenLabel_11, 
tokenLabel_12, 
tokenLabel_13, 
  };

#endif
/* JavaCC - OriginalChecksum=03a2c027a65c6db0f5e6c166d8a07b54 (do not edit this line) */
