/* Generated By:JavaCC: Do not edit this line. TokenManager.h Version 8.0.0 */
/* JavaCCOptions:STATIC=true,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef JAVACC_TOKEN_MANAGER_H
#define JAVACC_TOKEN_MANAGER_H

#include <iostream>
#include "JavaCC.h"
#include "Token.h"


/**
 * An implementation for this interface is generated by JavaCCParser.
 * The user is free to use any implementation of their choice.
 */

class TokenManager {
public:
  virtual       ~TokenManager() { }
  /** This gets the next token from the input stream.
   *  A token of kind 0 (<EOF>) should be returned on EOF.
   */
  virtual Token* getNextToken() = 0;
  virtual void   setParser(void* /*parser*/) {};
  virtual void   lexicalError() {
  	std::clog << "Lexical error encountered." << std::endl;
  }

};


#endif
/* JavaCC - OriginalChecksum=f587ba477292c62627ab925b2b32490b (do not edit this line) */
