/* Generated By:JavaCC: Do not edit this line. TokenManagerError.h Version 8.0.0 */
/* JavaCCOptions:STATIC=true,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef JAVACC_TOKEN_MANAGER_ERROR_H
#define JAVACC_TOKEN_MANAGER_ERROR_H

#include "JavaCC.h"


enum LexerErrors {
  LEXICAL_ERROR = 0,			// Lexical error occurred.
  STATIC_LEXER_ERROR = 1,		// An attempt was made to create a second instance of a  token manager.
  INVALID_LEXICAL_STATE = 2,	// Tried to change to an invalid lexical state.
  LOOP_DETECTED = 3,			// Detected (and bailed out of) an infinite loop in the token manager.
};

class TokenManagerError {
public:
  TokenManagerError();
  TokenManagerError(const JJString& message, int reason);
  TokenManagerError(bool EOFSeen, int lexState, int errorLine, int errorColumn, const JJString& errorAfter, JJChar curChar, int reason) ;
  virtual ~TokenManagerError();
  
  /**
   * Indicates the reason why the exception is thrown. It will have
   * one of the above 4 values.
   */
  int errorCode = -1;

  /**
   * Returns a detailed message for the Error when it is thrown by the
   * token manager to indicate a lexical error.
   * Parameters :
   *    EOFSeen     : indicates if EOF caused the lexical error
   *    curLexState : lexical state in which this error occurred
   *    errorLine   : line number when the error occurred
   *    errorColumn : column number when the error occurred
   *    errorAfter  : prefix that was seen before this error occurred
   *    curchar     : the offending character
   * Note: You can customize the lexical error message by modifying this method.
   */
   virtual JJString lexicalError(bool EOFSeen, int lexState, int errorLine, int errorColumn, const JJString& errorAfter, JJChar curChar);

  /**
   * You can also modify the body of this method to customize your error messages.
   * For example, cases like LOOP_DETECTED and INVALID_LEXICAL_STATE are not
   * of end-users concern, so you can return something like :
   *
   *     "Internal Error : Please file a bug report .... "
   *
   * from this method for such cases in the release version of your parser.
   */
public:
  JJString getMessage() ;
  
private:
  JJString message;

};


#endif
/* JavaCC - OriginalChecksum=bf0b7f74d4517064c46831038d8d72b7 (do not edit this line) */
