/* Generated By:JavaCC: Do not edit this line. Token.h Version 8.0.0 */
/* JavaCCOptions:STATIC=true,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef JAVACC_TOKEN_H
#define JAVACC_TOKEN_H

#include "JavaCC.h"



/**
 * Describes the input token stream.
 */

class Token
{
public:
           Token() {}
  virtual ~Token() {}

  /**
   * An integer that describes the kind of this token.  This numbering
   * system is determined by JavaCCParser, and a table of these numbers is
   * stored in the file ...Constants.java.
   */
  virtual int& 				kind() = 0;	
  virtual int& 				beginLine() = 0;		// The line number of the first character of this Token.
  virtual int& 				beginColumn() = 0;		// The column number of the first character of this Token.
  virtual int& 				endLine() = 0;			// The line number of the last character of this Token.
  virtual int& 				endColumn() = 0;		// The column number of the last character of this Token.
  virtual JJString& 		image() = 0;			// The string image of the token.
  
  /**
   * A reference to the next regular (non-special) token from the input
   * stream.  If this is the last token from the input stream, or if the
   * token manager has not read tokens beyond this one, this field is
   * set to NULL.  This is true only if this token is also a regular
   * token.  Otherwise, see below for a description of the contents of
   * this field.
   */
  virtual Token*& 			next() = 0;

  /**
   * This field is used to access special tokens that occur prior to this
   * token, but after the immediately preceding regular (non-special) token.
   * If there are no such special tokens, this field is set to NULL.
   * When there are more than one such special token, this field refers
   * to the last of these special tokens, which in turn refers to the next
   * previous special token through its specialToken field, and so on
   * until the first special token (whose specialToke_ field is NULL).
   * The next fields of special tokens refer to other special tokens that
   * immediately follow it (without an intervening regular token).  If there
   * is no such token, this field is NULL.
   */
  virtual Token*& 			specialToken() = 0;
  
  virtual const int& 		kind() const = 0;	
  virtual const int& 		beginLine() const = 0;
  virtual const int& 		beginColumn() const = 0;
  virtual const int& 		endLine() const = 0;
  virtual const int& 		endColumn() const = 0;
  virtual const JJString& 	image() const = 0;
  virtual const Token*	 	next() const = 0;
  virtual const Token*	 	specialToken() const = 0;

  virtual const JJString& 	toString() = 0;
};


#endif
/* JavaCC - OriginalChecksum=f4ec032a6e2611aee07624da9efe09fa (do not edit this line) */
