/* Generated By:JavaCC: Do not edit this line. SPLParserDefaultVisitor.java Version 8.0.0 */
package vst;

public class SPLParserDefaultVisitor implements SPLParserVisitor{
  public void defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return;
  }
  public void visit(SimpleNode node, Object data){
    defaultVisit(node, data);
  }
  public void visit(ASTAssignment node, Object data){
    defaultVisit(node, data);
  }
  public void visit(ASTOrNode node, Object data){
    defaultVisit(node, data);
  }
  public void visit(ASTAndNode node, Object data){
    defaultVisit(node, data);
  }
  public void visit(ASTBitwiseOrNode node, Object data){
    defaultVisit(node, data);
  }
  public void visit(ASTBitwiseXorNode node, Object data){
    defaultVisit(node, data);
  }
  public void visit(ASTBitwiseAndNode node, Object data){
    defaultVisit(node, data);
  }
  public void visit(ASTEQNode node, Object data){
    defaultVisit(node, data);
  }
  public void visit(ASTNENode node, Object data){
    defaultVisit(node, data);
  }
  public void visit(ASTLTNode node, Object data){
    defaultVisit(node, data);
  }
  public void visit(ASTGTNode node, Object data){
    defaultVisit(node, data);
  }
  public void visit(ASTLENode node, Object data){
    defaultVisit(node, data);
  }
  public void visit(ASTGENode node, Object data){
    defaultVisit(node, data);
  }
  public void visit(ASTAddNode node, Object data){
    defaultVisit(node, data);
  }
  public void visit(ASTSubtractNode node, Object data){
    defaultVisit(node, data);
  }
  public void visit(ASTMulNode node, Object data){
    defaultVisit(node, data);
  }
  public void visit(ASTDivNode node, Object data){
    defaultVisit(node, data);
  }
  public void visit(ASTModNode node, Object data){
    defaultVisit(node, data);
  }
  public void visit(ASTBitwiseComplNode node, Object data){
    defaultVisit(node, data);
  }
  public void visit(ASTNotNode node, Object data){
    defaultVisit(node, data);
  }
  public void visit(ASTIntConstNode node, Object data){
    defaultVisit(node, data);
  }
  public void visit(ASTTrueNode node, Object data){
    defaultVisit(node, data);
  }
  public void visit(ASTFalseNode node, Object data){
    defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=a64be5dab4385478cf0794aee3448459 (do not edit this line) */
