/* Generated By:JavaCC: Do not edit this line. SPLParserVisitor.java Version 8.0.0 */
package vst;

public interface SPLParserVisitor
{
  public void visit(SimpleNode node, Object data);
  public void visit(ASTAssignment node, Object data);
  public void visit(ASTOrNode node, Object data);
  public void visit(ASTAndNode node, Object data);
  public void visit(ASTBitwiseOrNode node, Object data);
  public void visit(ASTBitwiseXorNode node, Object data);
  public void visit(ASTBitwiseAndNode node, Object data);
  public void visit(ASTEQNode node, Object data);
  public void visit(ASTNENode node, Object data);
  public void visit(ASTLTNode node, Object data);
  public void visit(ASTGTNode node, Object data);
  public void visit(ASTLENode node, Object data);
  public void visit(ASTGENode node, Object data);
  public void visit(ASTAddNode node, Object data);
  public void visit(ASTSubtractNode node, Object data);
  public void visit(ASTMulNode node, Object data);
  public void visit(ASTDivNode node, Object data);
  public void visit(ASTModNode node, Object data);
  public void visit(ASTBitwiseComplNode node, Object data);
  public void visit(ASTNotNode node, Object data);
  public void visit(ASTIntConstNode node, Object data);
  public void visit(ASTTrueNode node, Object data);
  public void visit(ASTFalseNode node, Object data);
}
/* JavaCC - OriginalChecksum=434cabe1bf32521294f4fe7c52904623 (do not edit this line) */
