/* Generated By:JavaCC: Do not edit this line. SPLParserTokenManager.java Version 8.0.0 */
package vst;


public class SPLParserTokenManager  implements SPLParserConstants {

protected static boolean moveToNextChar() {
  try {
    curChar = input_stream.readChar();
  } catch(java.io.IOException e) {
    return false;
  }
  return true;
}



    /** Constructor. */
    public SPLParserTokenManager(SimpleCharStream stream){

      if (input_stream != null)
        throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);

    input_stream = stream;
  }

  /** Constructor. */
  public SPLParserTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  
  static public void ReInit(SimpleCharStream stream)
  {

    jjmatchedPos = 0;
    curLexState = defaultLexState;
    input_stream = stream;
  }

  /** Reinitialise parser. */
  static public void ReInit(SimpleCharStream stream, int lexState)
  
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public static void SwitchTo(int lexState) {
    curLexState = lexState;
  }

private static  int jjRunStringLiteralMatch() {
  int curPos = 0;
  int key = (int)curLexState << 16 | curChar;
  int startState = jjInitStates[curLexState];
  if (startAndSize.containsKey(key)) {
    int[] arr = startAndSize.get(key);
    int index = arr[0];
    for (int i = 0; i < arr[1]; i++) {
      int len = stringLiterals[index++];
      int ignoreCase = stringLiterals[index++];
      do {
        if (curChar != stringLiterals[index + curPos] &&
            (ignoreCase == 0 || curChar != stringLiterals[index + len + curPos])) break;
        if (++curPos == len) break;
        if (!moveToNextChar()) {
          --curPos;
          break;
        }
      } while(curPos < len);
      if (curPos == len) {
        jjmatchedKind = stringLiterals[index + len + (ignoreCase * len)];
        jjmatchedPos = curPos;
        startState = stringLiterals[index + len + (ignoreCase * len) + 1];
        if (!moveToNextChar()) {
          return curPos;
        }
        curPos++;
        break;
      } else {
        index += len + (ignoreCase * len) + 2;
        input_stream.backup(curPos + 1);
        curPos = 0;
        if (!moveToNextChar()) {
          assert(false);
        }
      }
    }
  } else {
  }
  return jjMoveNfa(startState, curPos);
}

private static   int[] stateSet = new int[3];
private static   int[] newStateSet = new int[3];
private static   long[] moved = new long[3];
private static  long moveIndex = 1L;

private static final int jjMoveNfa(int startState, int curPos) {

  if (startState < 0) {
    return curPos;
  }

  // We have a long array indexed by the NFA state number to roughly indicate
  // the input position so when the input reaches part Long.MAX_VALUE (which
  // should be extremely rare), we need to reset them all back to zero.
  if (++moveIndex == Long.MAX_VALUE) {
    for (int i = 0; i < 3; i++) moved[i] = 0L;
    moveIndex = 1L;
  }

  // We initialize the kind to MAX value so that when a match is found, we can
  // simply check if it's less than the current match and store it in that
  // case. This helps implement the 'first occurring' rule properly.
  int cnt = 0;
  stateSet[cnt++] = startState;
  moved[startState] = moveIndex;
 
  // Some NFA states have epsilon transitions (move on empty string). So we
  // just start with all of them. Note that the nextStates array already adds
  // the epsilon closure. Only the initial state needs to do this explicitly.
  for (int s : jjcompositeState[startState]) { 
    if (moved[s] != moveIndex) {
      stateSet[cnt++] = s;
      moved[s] = moveIndex;
    }
  }

  do {
    int newCnt = 0;
    int kind = Integer.MAX_VALUE;
    if (++moveIndex == Long.MAX_VALUE) {
      for (int i = 0; i < 3; i++) moved[i] = 0L;
      moveIndex = 1L;
    }

    int vectorIndex = curChar >> 6;
    long bitpattern = (1L << (curChar & 0x3f));
    do {
      int state = stateSet[--cnt];
      if ((jjChars[state][vectorIndex] & bitpattern) != 0L) {
        // Current input character can move this NFA state. So add all the
        // next states of the current states for use with the next input char.
        for (int newState : jjnextStateSet[state]) {
          if (moved[newState] != moveIndex) {
            // We add each state only once.
            newStateSet[newCnt++] = newState;
            moved[newState] = moveIndex;
          }
        }
        int newKind = jjmatchKinds[state];
        if (kind > newKind) {
          // It's a state so store the matched kind if it's smaller than
          // what's already matched.
          kind = newKind;
        }
      }
    } while (cnt > 0);

    if (kind != Integer.MAX_VALUE) {
      // We found a match. So remember the kind and position of the match.
      jjmatchedKind = kind;
      jjmatchedPos = curPos;
      // Reset the kind to max value so we can contine looking for a longer
      // match.
      kind = Integer.MAX_VALUE;
    }

    // Swap the current and next state sets.
    int[] tmp = stateSet;
    stateSet = newStateSet;
    newStateSet = tmp;
    // Reset the number of states.
    cnt = newCnt;
    if (newCnt == 0) {
      // There were no transitions from any of the current states on the
      // current input. So we are done.
      return curPos;
    }
    // Read the next character and try to continue running the NFA.
    if (!moveToNextChar()) {
      // EOF reached!
      return curPos;
    }
    ++curPos;
  } while (cnt > 0);

  assert(false) :
      "Interal error. Please submit a bug at: http://javacc.java.net.";
  return curPos;
}

private static  int defaultLexState = 0;
protected static  int curLexState = 0;
private static  int jjmatchedPos;
private static  int jjmatchedKind;
private static  StringBuilder jjimage = new StringBuilder();
private static StringBuilder image = jjimage;
private static int jjimageLen;
private static int lengthOfMatch;
protected static int curChar;
protected static  SimpleCharStream input_stream;

public static boolean isToken(int kind) {
  return (jjtoToken[kind >> 6] & (1L << (kind & 0x3f))) != 0L;
}

public static final boolean isSkip(int kind) {
  return (jjtoSkip[kind >> 6] & (1L << (kind & 0x3f))) != 0L;
}

public static boolean isSpecial(int kind) {
  return (jjtoSpecial[kind >> 6] & (1L << (kind & 0x3f))) != 0L;
}

public static boolean isMore(int kind) {
  return (jjtoMore[kind >> 6] & (1L << (kind & 0x3f))) != 0L;
}

protected static  Token jjFillToken() {
  Token t;
  String curTokenImage;
  int beginLine;
  int endLine;
  int beginColumn;
  int endColumn;
  if (jjmatchedPos < 0) {
    if (image == null) {
      curTokenImage = "";
    } else {
      curTokenImage = image.toString();
    }
    beginLine = endLine = input_stream.getEndLine();
    beginColumn = endColumn = input_stream.getEndColumn();
  } else {
    String im = jjstrLiteralImages[jjmatchedKind];
    curTokenImage = (im == null) ? input_stream.GetImage() : im;
    beginLine = input_stream.getBeginLine();
    beginColumn = input_stream.getBeginColumn();
    endLine = input_stream.getEndLine();
    endColumn = input_stream.getEndColumn();
  }

   t = Token.newToken(jjmatchedKind);
   t.kind = jjmatchedKind;
   t.image = curTokenImage;

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

/** Get the next Token. */
public static  Token getNextToken() {
  Token specialToken = null;
  Token matchedToken;
  int lastReadPosition = 0;

  EOFLoop:
  for (;;) {
    // First see if we have any input at all.
    try {
      curChar = input_stream.BeginToken();
    } catch(Exception e) {
      // No input. So return EOF token.
      jjmatchedKind = EOF;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      matchedToken.specialToken = specialToken;
      return matchedToken;
    }

    // Set matched kind to a MAX VALUE to implement largest, first occuring rule
    // i.e., smallest kind value matched should be used.
    image = jjimage;
    image.setLength(0);
    jjimageLen = 0;

    MoreLoop: for (;;) {
      jjmatchedKind = Integer.MAX_VALUE;
      jjmatchedPos = 0;
      lastReadPosition = jjRunStringLiteralMatch();
      if (jjmatchedPos == 0 && jjmatchedKind > canMatchAnyChar[curLexState]) {
        jjmatchedKind = canMatchAnyChar[curLexState];
      }

      if (jjmatchedKind != Integer.MAX_VALUE) {
        // We have a match!
  
        // Put back any characters looked ahead.
        input_stream.backup(lastReadPosition - jjmatchedPos);
        if (isToken(jjmatchedKind)) {
          // Matched kind is a real TOKEN.
          matchedToken = jjFillToken();
          matchedToken.specialToken = specialToken;
          TokenLexicalActions(matchedToken);
          if (jjnewLexState[jjmatchedKind] != -1) {
            curLexState = jjnewLexState[jjmatchedKind];
          }
          return matchedToken;
        } else if (isSkip(jjmatchedKind) || isSpecial(jjmatchedKind)) {
          // Matched kind is a SKIP or SPECIAL_TOKEN.
          if (isSpecial(jjmatchedKind)) {
            matchedToken = jjFillToken();
            if (specialToken == null) {
              specialToken = matchedToken;
            } else {
              matchedToken.specialToken = specialToken;
              specialToken = (specialToken.next = matchedToken);
            }
            SkipLexicalActions(matchedToken);
          } else {
            SkipLexicalActions(null);
          }
          if (jjnewLexState[jjmatchedKind] != -1) {
            curLexState = jjnewLexState[jjmatchedKind];
          }
          continue EOFLoop;
        }
        // Here it's a MORE.
        MoreLexicalActions();
        if (jjnewLexState[jjmatchedKind] != -1) {
          curLexState = jjnewLexState[jjmatchedKind];
        }
        lastReadPosition = 0;
        jjmatchedKind = Integer.MAX_VALUE;
        try {
          curChar = input_stream.readChar();
          continue;
        }
        catch (java.io.IOException e1) { }
      }
      reportError(lastReadPosition);
    }
  }
}

protected static  void reportError(int lastReadPosition) {
  int error_line = input_stream.getEndLine();
  int error_column = input_stream.getEndColumn();
  String error_after = null;
  boolean EOFSeen = false;
  try {
    input_stream.readChar();
    input_stream.backup(1);
  } catch (java.io.IOException e1) {
    EOFSeen = true;
    error_after = lastReadPosition <= 1 ? "" : input_stream.GetImage();
    if (curChar == '\n' || curChar == '\r') {
       error_line++;
       error_column = 0;
    }
    else
       error_column++;
  }
  if (!EOFSeen) {
    input_stream.backup(1);
    error_after = lastReadPosition <= 1 ? "" : input_stream.GetImage();
  }
  throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column,
                          error_after, curChar, TokenMgrError.LEXICAL_ERROR);
}

private static final java.util.Map<Integer, int[]> startAndSize =
    new java.util.HashMap<Integer, int[]>();


private static final long[][] jjChars = new long[3][];
private static void InitNfaData() {
  for (int i = 0; i < 3; i++) {
    jjChars[i] = new long[1024];
    int ind = 0;
    // We originally generate something like RLE for the static arrays and
    // we actually expannd them here.
    for (int j = 0; j < jjCharData[i].length; j += 2) {
      for (int k = 0; k < (int)jjCharData[i][j]; k++) {
        jjChars[i][ind++] = jjCharData[i][j + 1];
      }
    }
  }
}
public static String[] lexStateNames = {
"DEFAULT"
};
private static final int[] stringLiterals = {
1, 0, 9, 2, -1, 
1, 0, 10, 3, -1, 
1, 0, 12, 5, -1, 
1, 0, 13, 4, -1, 
1, 0, 94, 14, -1, 
1, 0, 32, 1, -1, 
2, 0, 33, 61, 17, -1, 
1, 0, 33, 28, -1, 
7, 0, 98, 111, 111, 108, 101, 97, 110, 7, 2, 
1, 0, 37, 26, -1, 
4, 0, 101, 108, 115, 101, 37, 2, 
2, 0, 38, 38, 12, -1, 
1, 0, 38, 15, -1, 
5, 0, 102, 97, 108, 115, 101, 32, 2, 
1, 0, 40, 29, -1, 
3, 0, 105, 110, 116, 6, 2, 
2, 0, 105, 102, 36, 2, 
1, 0, 41, 30, -1, 
1, 0, 42, 24, -1, 
1, 0, 43, 22, -1, 
1, 0, 45, 23, -1, 
1, 0, 47, 25, -1, 
4, 0, 114, 101, 97, 100, 39, 2, 
4, 0, 116, 114, 117, 101, 31, 2, 
5, 0, 119, 114, 105, 116, 101, 40, 2, 
5, 0, 119, 104, 105, 108, 101, 38, 2, 
1, 0, 58, 33, -1, 
1, 0, 59, 9, -1, 
1, 0, 123, 34, -1, 
2, 0, 124, 124, 11, -1, 
1, 0, 124, 13, -1, 
2, 0, 60, 61, 20, -1, 
1, 0, 60, 18, -1, 
2, 0, 61, 61, 16, -1, 
1, 0, 61, 10, -1, 
1, 0, 125, 35, -1, 
2, 0, 62, 61, 21, -1, 
1, 0, 62, 19, -1, 
1, 0, 126, 27, -1};
static void InitStringLiteralData() {
startAndSize.put(9, new int[]{0, 1});
startAndSize.put(10, new int[]{5, 1});
startAndSize.put(12, new int[]{10, 1});
startAndSize.put(13, new int[]{15, 1});
startAndSize.put(94, new int[]{20, 1});
startAndSize.put(32, new int[]{25, 1});
startAndSize.put(33, new int[]{30, 2});
startAndSize.put(98, new int[]{41, 1});
startAndSize.put(37, new int[]{52, 1});
startAndSize.put(101, new int[]{57, 1});
startAndSize.put(38, new int[]{65, 2});
startAndSize.put(102, new int[]{76, 1});
startAndSize.put(40, new int[]{85, 1});
startAndSize.put(105, new int[]{90, 2});
startAndSize.put(41, new int[]{103, 1});
startAndSize.put(42, new int[]{108, 1});
startAndSize.put(43, new int[]{113, 1});
startAndSize.put(45, new int[]{118, 1});
startAndSize.put(47, new int[]{123, 1});
startAndSize.put(114, new int[]{128, 1});
startAndSize.put(116, new int[]{136, 1});
startAndSize.put(119, new int[]{144, 2});
startAndSize.put(58, new int[]{162, 1});
startAndSize.put(59, new int[]{167, 1});
startAndSize.put(123, new int[]{172, 1});
startAndSize.put(124, new int[]{177, 2});
startAndSize.put(60, new int[]{188, 2});
startAndSize.put(61, new int[]{199, 2});
startAndSize.put(125, new int[]{210, 1});
startAndSize.put(62, new int[]{215, 2});
startAndSize.put(126, new int[]{226, 1});
}
private static final long[][] jjCharData = {
new long[] {1, 287948901175001088L},
new long[] {1, 0L, 1, 576460743847706622L},
new long[] {1, 287948901175001088L, 1, 576460743847706622L}};
private static final int[][] jjcompositeState = {
new int[]{}, 
new int[]{0, 1}, 
new int[]{}};
private static final int[] jjmatchKinds = {
8, 
41, 
41};
private static final int[][] jjnextStateSet = {
new int[]{0}, 
new int[]{2}, 
new int[]{2}};
private static final int[] jjInitStates  = {
1};
private static final int[] canMatchAnyChar = {
2147483647};
public static final String[] jjstrLiteralImages = {
null
, 
"\40", 
"\11", 
"\12", 
"\15", 
"\14", 
"\151\156\164", 
"\142\157\157\154\145\141\156", 
null
, 
"\73", 
"\75", 
"\174\174", 
"\46\46", 
"\174", 
"\136", 
"\46", 
"\75\75", 
"\41\75", 
"\74", 
"\76", 
"\74\75", 
"\76\75", 
"\53", 
"\55", 
"\52", 
"\57", 
"\45", 
"\176", 
"\41", 
"\50", 
"\51", 
"\164\162\165\145", 
"\146\141\154\163\145", 
"\72", 
"\173", 
"\175", 
"\151\146", 
"\145\154\163\145", 
"\167\150\151\154\145", 
"\162\145\141\144", 
"\167\162\151\164\145", 
null
, 
null
, 
null
};
private static final long[] jjtoSkip = {
35184372088894L};
private static final long[] jjtoSpecial = {
35184372088832L};
private static final long[] jjtoMore = {
35184372088832L};
private static final long[] jjtoToken = {
52776558133185L};
private static final int[] jjnewLexState = {
-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1};
static void TokenLexicalActions(Token matchedToken) {
  switch(matchedToken.kind) {
    default: break;
  }
}
static void SkipLexicalActions(Token matchedToken) {
  switch(jjmatchedKind) {
    default: break;
  }
  switch(jjmatchedKind) {
    default: break;
  }
}
static void MoreLexicalActions() {
jjimageLen += (lengthOfMatch = jjmatchedPos + 1);
  switch(jjmatchedKind) {
    default: break;
  }
}
static {
  InitStringLiteralData();
  InitNfaData(); } 
}
/* JavaCC - OriginalChecksum=396956cbd82fd2c4fa72d81248869001 (do not edit this line) */
