/* Generated By:JJTree: Do not edit this line. ASTAddNode.h Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include "SimpleNode.h"

class SPLParser;

class ASTAddNode : public SimpleNode {
public: 
  ASTAddNode(int id);
  ASTAddNode(SPLParser *parser, int id);
  virtual ~ASTAddNode();

  /** Accept the visitor. **/
  virtual void jjtAccept(SPLParserVisitor *visitor, void* data) const ;
};

/* JavaCC - OriginalChecksum=572d33007c001de674d02f305139b503 (do not edit this line) */
