/* Generated By:JJTree: Do not edit this line. ASTAssignment.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTAssignment.h"
#include "SPLParserVisitor.h"

  
  ASTAssignment::ASTAssignment(int id) : SimpleNode(id) {
  }
  ASTAssignment::ASTAssignment(SPLParser *parser, int id) : SimpleNode(parser, id) {
  }
  ASTAssignment::~ASTAssignment() {
  }

  /** Accept the visitor. **/
  void ASTAssignment::jjtAccept(SPLParserVisitor *visitor, void* data) const {
    visitor->visit(this, data);
  }

/* JavaCC - OriginalChecksum=f62acac4cbe77263da0d162f63ddccfc (do not edit this line) */
