/* Generated By:JJTree: Do not edit this line. ASTBitwiseOrNode.h Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include "SimpleNode.h"

class SPLParser;

class ASTBitwiseOrNode : public SimpleNode {
public: 
  ASTBitwiseOrNode(int id);
  ASTBitwiseOrNode(SPLParser *parser, int id);
  virtual ~ASTBitwiseOrNode();

  /** Accept the visitor. **/
  virtual void jjtAccept(SPLParserVisitor *visitor, void* data) const ;
};

/* JavaCC - OriginalChecksum=4fad56c6b2ed992f1c59c6435117a3ff (do not edit this line) */
