/* Generated By:JJTree: Do not edit this line. ASTBitwiseAndNode.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTBitwiseAndNode.h"
#include "SPLParserVisitor.h"

  
  ASTBitwiseAndNode::ASTBitwiseAndNode(int id) : SimpleNode(id) {
  }
  ASTBitwiseAndNode::ASTBitwiseAndNode(SPLParser *parser, int id) : SimpleNode(parser, id) {
  }
  ASTBitwiseAndNode::~ASTBitwiseAndNode() {
  }

  /** Accept the visitor. **/
  void ASTBitwiseAndNode::jjtAccept(SPLParserVisitor *visitor, void* data) const {
    visitor->visit(this, data);
  }

/* JavaCC - OriginalChecksum=29917804e566e2ba9e6883014b43a287 (do not edit this line) */
