/* Generated By:JJTree: Do not edit this line. ASTDivNode.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTDivNode.h"
#include "SPLParserVisitor.h"

  
  ASTDivNode::ASTDivNode(int id) : SimpleNode(id) {
  }
  ASTDivNode::ASTDivNode(SPLParser *parser, int id) : SimpleNode(parser, id) {
  }
  ASTDivNode::~ASTDivNode() {
  }

  /** Accept the visitor. **/
  void ASTDivNode::jjtAccept(SPLParserVisitor *visitor, void* data) const {
    visitor->visit(this, data);
  }

/* JavaCC - OriginalChecksum=7b50ca5a2af085c95372bf1a9af23f75 (do not edit this line) */
