/* Generated By:JJTree: Do not edit this line. ASTEQNode.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTEQNode.h"
#include "SPLParserVisitor.h"

  
  ASTEQNode::ASTEQNode(int id) : SimpleNode(id) {
  }
  ASTEQNode::ASTEQNode(SPLParser *parser, int id) : SimpleNode(parser, id) {
  }
  ASTEQNode::~ASTEQNode() {
  }

  /** Accept the visitor. **/
  void ASTEQNode::jjtAccept(SPLParserVisitor *visitor, void* data) const {
    visitor->visit(this, data);
  }

/* JavaCC - OriginalChecksum=cacbd74a76bc83d1678f39fe0687385c (do not edit this line) */
