/* Generated By:JJTree: Do not edit this line. ASTFalseNode.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTFalseNode.h"
#include "SPLParserVisitor.h"

  
  ASTFalseNode::ASTFalseNode(int id) : SimpleNode(id) {
  }
  ASTFalseNode::ASTFalseNode(SPLParser *parser, int id) : SimpleNode(parser, id) {
  }
  ASTFalseNode::~ASTFalseNode() {
  }

  /** Accept the visitor. **/
  void ASTFalseNode::jjtAccept(SPLParserVisitor *visitor, void* data) const {
    visitor->visit(this, data);
  }

/* JavaCC - OriginalChecksum=12c4444c1749326a09f9b6de99200500 (do not edit this line) */
