/* Generated By:JJTree: Do not edit this line. ASTGTNode.h Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include "SimpleNode.h"

class SPLParser;

class ASTGTNode : public SimpleNode {
public: 
  ASTGTNode(int id);
  ASTGTNode(SPLParser *parser, int id);
  virtual ~ASTGTNode();

  /** Accept the visitor. **/
  virtual void jjtAccept(SPLParserVisitor *visitor, void* data) const ;
};

/* JavaCC - OriginalChecksum=0f59f400f3608e6e2e68c3e30b05f0d3 (do not edit this line) */
