/* Generated By:JJTree: Do not edit this line. ASTModNode.h Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include "SimpleNode.h"

class SPLParser;

class ASTModNode : public SimpleNode {
public: 
  ASTModNode(int id);
  ASTModNode(SPLParser *parser, int id);
  virtual ~ASTModNode();

  /** Accept the visitor. **/
  virtual void jjtAccept(SPLParserVisitor *visitor, void* data) const ;
};

/* JavaCC - OriginalChecksum=6334a24f3d8ffe7a7ad69725f0627171 (do not edit this line) */
