/* Generated By:JJTree: Do not edit this line. ASTNotNode.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTNotNode.h"
#include "SPLParserVisitor.h"

  
  ASTNotNode::ASTNotNode(int id) : SimpleNode(id) {
  }
  ASTNotNode::ASTNotNode(SPLParser *parser, int id) : SimpleNode(parser, id) {
  }
  ASTNotNode::~ASTNotNode() {
  }

  /** Accept the visitor. **/
  void ASTNotNode::jjtAccept(SPLParserVisitor *visitor, void* data) const {
    visitor->visit(this, data);
  }

/* JavaCC - OriginalChecksum=a83b3856f08abec255fc9d8ff6119844 (do not edit this line) */
