/* Generated By:JJTree: Do not edit this line. ASTSubtractNode.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTSubtractNode.h"
#include "SPLParserVisitor.h"

  
  ASTSubtractNode::ASTSubtractNode(int id) : SimpleNode(id) {
  }
  ASTSubtractNode::ASTSubtractNode(SPLParser *parser, int id) : SimpleNode(parser, id) {
  }
  ASTSubtractNode::~ASTSubtractNode() {
  }

  /** Accept the visitor. **/
  void ASTSubtractNode::jjtAccept(SPLParserVisitor *visitor, void* data) const {
    visitor->visit(this, data);
  }

/* JavaCC - OriginalChecksum=7a9c34b5e21bdcc7cd5c8d1457a4ac2d (do not edit this line) */
