/* Generated By:JJTree: Do not edit this line. ASTTrueNode.h Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include "SimpleNode.h"

class SPLParser;

class ASTTrueNode : public SimpleNode {
public: 
  ASTTrueNode(int id);
  ASTTrueNode(SPLParser *parser, int id);
  virtual ~ASTTrueNode();

  /** Accept the visitor. **/
  virtual void jjtAccept(SPLParserVisitor *visitor, void* data) const ;
};

/* JavaCC - OriginalChecksum=20da5b79d10528c3022c1ef341304954 (do not edit this line) */
