/* Generated By:JJTree: Do not edit this line. ASTTrueNode.cc Version 8.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTTrueNode.h"
#include "SPLParserVisitor.h"

  
  ASTTrueNode::ASTTrueNode(int id) : SimpleNode(id) {
  }
  ASTTrueNode::ASTTrueNode(SPLParser *parser, int id) : SimpleNode(parser, id) {
  }
  ASTTrueNode::~ASTTrueNode() {
  }

  /** Accept the visitor. **/
  void ASTTrueNode::jjtAccept(SPLParserVisitor *visitor, void* data) const {
    visitor->visit(this, data);
  }

/* JavaCC - OriginalChecksum=8c52b4b1477a063ee0027be37e4a1986 (do not edit this line) */
