/* Generated By:JJTree,JavaCC: Do not edit this line. SPLParserConstants.h Version 8.0.0 */
#pragma once


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGenCPP#start()
 */
#include "JavaCC.h"

  /** End of File. */
const  int _EOF = 0;
  /** RegularExpression Id. */
const  int INT = 6;
  /** RegularExpression Id. */
const  int BOOL = 7;
  /** RegularExpression Id. */
const  int INTEGER_LITERAL = 8;
  /** RegularExpression Id. */
const  int IDENTIFIER = 41;
  /** RegularExpression Id. */
const  int LETTER = 42;
  /** RegularExpression Id. */
const  int DIGIT = 43;

  /** Lexical state. */
const  int DEFAULT = 0;

  /** Literal token values. */
  static const JJChar tokenImage_arr_0[] = 
{0x3c, 0x45, 0x4f, 0x46, 0x3e, 0};
  static const JJChar tokenImage_arr_1[] = 
{0x22, 0x20, 0x22, 0};
  static const JJChar tokenImage_arr_2[] = 
{0x22, 0x9, 0x22, 0};
  static const JJChar tokenImage_arr_3[] = 
{0x22, 0xa, 0x22, 0};
  static const JJChar tokenImage_arr_4[] = 
{0x22, 0xd, 0x22, 0};
  static const JJChar tokenImage_arr_5[] = 
{0x22, 0xc, 0x22, 0};
  static const JJChar tokenImage_arr_6[] = 
{0x22, 0x69, 0x6e, 0x74, 0x22, 0};
  static const JJChar tokenImage_arr_7[] = 
{0x22, 0x62, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x22, 0};
  static const JJChar tokenImage_arr_8[] = 
{0x22, 0x3c, 0x49, 0x4e, 0x54, 0x45, 0x47, 0x45, 0x52, 0x5f, 0x4c, 0x49, 0x54, 0x45, 0x52, 0x41, 0x4c, 0x3e, 0x22, 0};
  static const JJChar tokenImage_arr_9[] = 
{0x22, 0x3b, 0x22, 0};
  static const JJChar tokenImage_arr_10[] = 
{0x22, 0x3d, 0x22, 0};
  static const JJChar tokenImage_arr_11[] = 
{0x22, 0x7c, 0x7c, 0x22, 0};
  static const JJChar tokenImage_arr_12[] = 
{0x22, 0x26, 0x26, 0x22, 0};
  static const JJChar tokenImage_arr_13[] = 
{0x22, 0x7c, 0x22, 0};
  static const JJChar tokenImage_arr_14[] = 
{0x22, 0x5e, 0x22, 0};
  static const JJChar tokenImage_arr_15[] = 
{0x22, 0x26, 0x22, 0};
  static const JJChar tokenImage_arr_16[] = 
{0x22, 0x3d, 0x3d, 0x22, 0};
  static const JJChar tokenImage_arr_17[] = 
{0x22, 0x21, 0x3d, 0x22, 0};
  static const JJChar tokenImage_arr_18[] = 
{0x22, 0x3c, 0x22, 0};
  static const JJChar tokenImage_arr_19[] = 
{0x22, 0x3e, 0x22, 0};
  static const JJChar tokenImage_arr_20[] = 
{0x22, 0x3c, 0x3d, 0x22, 0};
  static const JJChar tokenImage_arr_21[] = 
{0x22, 0x3e, 0x3d, 0x22, 0};
  static const JJChar tokenImage_arr_22[] = 
{0x22, 0x2b, 0x22, 0};
  static const JJChar tokenImage_arr_23[] = 
{0x22, 0x2d, 0x22, 0};
  static const JJChar tokenImage_arr_24[] = 
{0x22, 0x2a, 0x22, 0};
  static const JJChar tokenImage_arr_25[] = 
{0x22, 0x2f, 0x22, 0};
  static const JJChar tokenImage_arr_26[] = 
{0x22, 0x25, 0x22, 0};
  static const JJChar tokenImage_arr_27[] = 
{0x22, 0x7e, 0x22, 0};
  static const JJChar tokenImage_arr_28[] = 
{0x22, 0x21, 0x22, 0};
  static const JJChar tokenImage_arr_29[] = 
{0x22, 0x28, 0x22, 0};
  static const JJChar tokenImage_arr_30[] = 
{0x22, 0x29, 0x22, 0};
  static const JJChar tokenImage_arr_31[] = 
{0x22, 0x74, 0x72, 0x75, 0x65, 0x22, 0};
  static const JJChar tokenImage_arr_32[] = 
{0x22, 0x66, 0x61, 0x6c, 0x73, 0x65, 0x22, 0};
  static const JJChar tokenImage_arr_33[] = 
{0x22, 0x3a, 0x22, 0};
  static const JJChar tokenImage_arr_34[] = 
{0x22, 0x7b, 0x22, 0};
  static const JJChar tokenImage_arr_35[] = 
{0x22, 0x7d, 0x22, 0};
  static const JJChar tokenImage_arr_36[] = 
{0x22, 0x69, 0x66, 0x22, 0};
  static const JJChar tokenImage_arr_37[] = 
{0x22, 0x65, 0x6c, 0x73, 0x65, 0x22, 0};
  static const JJChar tokenImage_arr_38[] = 
{0x22, 0x77, 0x68, 0x69, 0x6c, 0x65, 0x22, 0};
  static const JJChar tokenImage_arr_39[] = 
{0x22, 0x72, 0x65, 0x61, 0x64, 0x22, 0};
  static const JJChar tokenImage_arr_40[] = 
{0x22, 0x77, 0x72, 0x69, 0x74, 0x65, 0x22, 0};
  static const JJChar tokenImage_arr_41[] = 
{0x22, 0x3c, 0x49, 0x44, 0x45, 0x4e, 0x54, 0x49, 0x46, 0x49, 0x45, 0x52, 0x3e, 0x22, 0};
  static const JJChar tokenImage_arr_42[] = 
{0x22, 0x3c, 0x4c, 0x45, 0x54, 0x54, 0x45, 0x52, 0x3e, 0x22, 0};
  static const JJChar tokenImage_arr_43[] = 
{0x22, 0x3c, 0x44, 0x49, 0x47, 0x49, 0x54, 0x3e, 0x22, 0};
  static const JJChar* const tokenImage[] = {
tokenImage_arr_0, 
tokenImage_arr_1, 
tokenImage_arr_2, 
tokenImage_arr_3, 
tokenImage_arr_4, 
tokenImage_arr_5, 
tokenImage_arr_6, 
tokenImage_arr_7, 
tokenImage_arr_8, 
tokenImage_arr_9, 
tokenImage_arr_10, 
tokenImage_arr_11, 
tokenImage_arr_12, 
tokenImage_arr_13, 
tokenImage_arr_14, 
tokenImage_arr_15, 
tokenImage_arr_16, 
tokenImage_arr_17, 
tokenImage_arr_18, 
tokenImage_arr_19, 
tokenImage_arr_20, 
tokenImage_arr_21, 
tokenImage_arr_22, 
tokenImage_arr_23, 
tokenImage_arr_24, 
tokenImage_arr_25, 
tokenImage_arr_26, 
tokenImage_arr_27, 
tokenImage_arr_28, 
tokenImage_arr_29, 
tokenImage_arr_30, 
tokenImage_arr_31, 
tokenImage_arr_32, 
tokenImage_arr_33, 
tokenImage_arr_34, 
tokenImage_arr_35, 
tokenImage_arr_36, 
tokenImage_arr_37, 
tokenImage_arr_38, 
tokenImage_arr_39, 
tokenImage_arr_40, 
tokenImage_arr_41, 
tokenImage_arr_42, 
tokenImage_arr_43, 
  };

/* JavaCC - OriginalChecksum=83bbac91d9d0ea2efe034a93b01540ba (do not edit this line) */
