/* Generated By:JJTree: Do not edit this line. SimpleNode.h Version 8.0 */
/* JavaCCOptions:MULTI=false,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#pragma once

#include "Node.h"

namespace EG1 {

class SimpleNode : public Node {
public: 
  SimpleNode(int id);
  virtual ~SimpleNode();

};

}
/* JavaCC - OriginalChecksum=01069e99f32f8fb873029bd3b08e6d86 (do not edit this line) */
